package com.mycompany.lipadbantayoopdsa.userAuthentication;

import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.MainFlightDisplayManagers;
import com.mycompany.lipadbantayoopdsa.popupInterface.ManageBookingChoice;
import com.mycompany.lipadbantayoopdsa.popupInterface.fareEditor_M;
import java.io.*;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import java.time.*;
import java.time.format.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author justine
 */
public class AirlineManagerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AirlineManagerDashboard.class.getName());
    
    private String loggedInUsername;
    
    
    /**
     * Creates new form AirlineManagerDashboard
     */
    public AirlineManagerDashboard() {
        initComponents();
        
        
        
    }
    
    public AirlineManagerDashboard(String currentAirlineName, String currentAirlinePrefix) {
        initComponents();

       
        AIRLINE.setText(currentAirlineName);
        FLPREFIX.setText(currentAirlinePrefix);

        
        ManagerData data = findManagerDetailsByAirline(currentAirlineName);

        if (data != null) {
            MANAGER.setText(data.name);
        } else {
            MANAGER.setText("Manager"); // Fallback text
        }
    }
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        airlineNameText = new javax.swing.JLabel();
        iataCodeText = new javax.swing.JLabel();
        flPrefixText = new javax.swing.JLabel();
        btnManageFlts = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        MANAGER = new javax.swing.JLabel();
        AIRLINE = new javax.swing.JLabel();
        FLPREFIX = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFateManager = new javax.swing.JButton();
        btnBookingsManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 153, 204));
        title.setText("Airline Manager Details");

        airlineNameText.setText("Manager Name");

        iataCodeText.setText("Airline Name:");

        flPrefixText.setText("FL PREFIX");

        btnManageFlts.setBackground(new java.awt.Color(0, 153, 204));
        btnManageFlts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFlts.setText("Manage Flights");
        btnManageFlts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFltsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 153, 153));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        MANAGER.setText("jLabel3");

        AIRLINE.setText("jLabel3");

        FLPREFIX.setText("jLabel3");

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setForeground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        btnFateManager.setBackground(new java.awt.Color(0, 153, 204));
        btnFateManager.setForeground(new java.awt.Color(255, 255, 255));
        btnFateManager.setText("Edit Fare");
        btnFateManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFateManagerActionPerformed(evt);
            }
        });

        btnBookingsManager.setBackground(new java.awt.Color(0, 153, 204));
        btnBookingsManager.setForeground(new java.awt.Color(255, 255, 255));
        btnBookingsManager.setText("Manage Bookings");
        btnBookingsManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingsManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(airlineNameText)
                            .addComponent(iataCodeText)
                            .addComponent(flPrefixText))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FLPREFIX)
                            .addComponent(AIRLINE)
                            .addComponent(MANAGER)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnLogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnManageFlts, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFateManager, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBookingsManager)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBookingsManager, btnFateManager, btnManageFlts});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(title)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MANAGER)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(FLPREFIX))
                            .addComponent(AIRLINE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(airlineNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(flPrefixText))
                            .addComponent(iataCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageFlts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFateManager, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookingsManager))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBookingsManager, btnFateManager, btnManageFlts});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        

        // Get current timestamp in the exact format
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd | HH:mm:ss");
        String timestamp = now.format(formatter);

        try(BufferedWriter writer = new BufferedWriter(new FileWriter(AdminOperations.Database_logs_Path, true))) {
            
            writer.write(String.format("[%s]%n", timestamp));
            writer.write("EVENT  : LOGOUT \n");
            writer.write("ACTION : User Logged Out \n");
            writer.write("ACTOR  : " + MANAGER.getText() + "\n");
            writer.write("ROLE   : AIRLINE_MANAGER\n");
            writer.write("\n----------------------------------------\n\n");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing logout log: " + e.getMessage(),
                                          "File Error", JOptionPane.ERROR_MESSAGE);
        }

        new AuthenticationForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageFltsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFltsActionPerformed
        MainFlightDisplayManagers display = new MainFlightDisplayManagers(AIRLINE.getText().toString(), FLPREFIX.getText().toString());
        display.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnManageFltsActionPerformed

    private void btnFateManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFateManagerActionPerformed
        fareEditor_M display = new fareEditor_M(AIRLINE.getText().toString(), FLPREFIX.getText().toString());
        display.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFateManagerActionPerformed

    private void btnBookingsManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingsManagerActionPerformed
         ManageBookingChoice display = new ManageBookingChoice(AIRLINE.getText().toString(), FLPREFIX.getText().toString());
         display.setVisible(true);
         dispose();
    }//GEN-LAST:event_btnBookingsManagerActionPerformed
    
    public AirlineManagerDashboard(String username) {
        initComponents(); 

        ManagerData data = findManagerDetails(username);

        if (data != null) {
    
            MANAGER.setText(data.name);   
            AIRLINE.setText(data.airline);          
            FLPREFIX.setText(data.prefix);      
            }
        
        loggedInUsername = username;
    }
    
    private class ManagerData {
            String name;
            String airline;
            String username;
            String prefix;

            public ManagerData(String name, String airline, String username, String prefix) {
                this.name = name;
                this.airline = airline;
                this.username = username;
                this.prefix = prefix;
        }
    }
    
    
    private ManagerData findManagerDetails(String targetUsername) {
        

        try(BufferedReader reader = new BufferedReader(new FileReader(AdminOperations.Database_UserCredentials_Path))) {
            
            String line;

            
            String tempManager = "";
            String tempAirline = "";
            String tempUsername = "";
            String tempPrefix = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("MANAGER:")) {
                    tempManager = line.substring("MANAGER:".length()).trim();
                } else if (line.startsWith("AIRLINE:")) {
                    tempAirline = line.substring("AIRLINE:".length()).trim();
                } else if (line.startsWith("USERNAME:")) {
                    tempUsername = line.substring("USERNAME:".length()).trim();
                } else if (line.startsWith("PREFIX:")) {
                    tempPrefix = line.substring("PREFIX:".length()).trim();
                } else if (line.startsWith("----------------------------")) {
                   
                    if (tempUsername.equals(targetUsername)) {
                     
                        return new ManagerData(tempManager, tempAirline, tempUsername, tempPrefix);
                    }

        
                    tempManager = "";
                    tempAirline = "";
                    tempUsername = "";
                    tempPrefix = "";
                }
            }
        } catch (IOException e) {
            System.out.println("Error loading Data");
        }

        return null;
    }
    
    
    private ManagerData findManagerDetailsByAirline(String targetAirline) {
        

        try(BufferedReader reader = new BufferedReader(new FileReader(AdminOperations.Database_UserCredentials_Path))) {
            
            String line;
            String tempManager = "";
            String tempAirline = "";
            String tempUsername = "";
            String tempPrefix = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("MANAGER:")) {
                    tempManager = line.substring("MANAGER:".length()).trim();
                } else if (line.startsWith("AIRLINE:")) {
                    tempAirline = line.substring("AIRLINE:".length()).trim();
                } else if (line.startsWith("USERNAME:")) {
                    tempUsername = line.substring("USERNAME:".length()).trim();
                } else if (line.startsWith("PREFIX:")) {
                    tempPrefix = line.substring("PREFIX:".length()).trim();
                } else if (line.startsWith("----------------------------")) {

                    // CHECK: Does the AIRLINE match?
                    if (tempAirline.equalsIgnoreCase(targetAirline)) {
                        return new ManagerData(tempManager, tempAirline, tempUsername, tempPrefix);
                    }

                    // Reset for next block
                    tempManager = "";
                    tempAirline = "";
                    tempUsername = "";
                    tempPrefix = "";
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading credentials");
        }
        return null;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AirlineManagerDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AIRLINE;
    private javax.swing.JLabel FLPREFIX;
    private javax.swing.JLabel MANAGER;
    private javax.swing.JLabel airlineNameText;
    private javax.swing.JButton btnBookingsManager;
    private javax.swing.JButton btnFateManager;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageFlts;
    private javax.swing.JLabel flPrefixText;
    private javax.swing.JLabel iataCodeText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
