package com.mycompany.lipadbantayoopdsa.userAuthentication;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mycompany.lipadbantayoopdsa.MainFlightDisplayAdmin;
import com.mycompany.lipadbantayoopdsa.userAuthentication.AuthenticationForm;
import com.mycompany.lipadbantayoopdsa.userAuthentication.AirlineManagerDashboard;
import com.mycompany.lipadbantayoopdsa.MainFlightDisplayGuest;
import com.mycompany.lipadbantayoopdsa.MainFlightDisplayAdmin;
import com.mycompany.lipadbantayoopdsa.Logs.logs;
import java.nio.file.Paths;
import javax.swing.*;
import java.io.*;

/**
 *
 * @author justine
 */

public class LoginForm extends javax.swing.JFrame {

    private static final java.util.Map<String, String> USER_ROLES = new java.util.HashMap<>();
    static {
        USER_ROLES.put("admin", "ADMIN");
        USER_ROLES.put("manager", "AIRLINE_MANAGER");
        USER_ROLES.put("user", "USER");
}
   
 

/**
 * Reads user_credentials.txt from the project root directory.
 * Authenticates the provided username and password against the file data.
 * Returns the role string (ADMIN/AIRLINE_MANAGER/USER) or null if authentication fails.
 */
    private String authenticateUser(String username, String password) {
        String filePath = Paths.get(System.getProperty("user.dir"), 
                                        "src", "main", "java", "com", "mycompany", 
                                        "lipadbantayoopdsa", "userAuthentication", 
                                        "user_credentials.txt").toString();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String fileUsername = null;
            String filePassword = null;
            String fileRole = null;

            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;

                if (line.startsWith("USERNAME:")) {
                    fileUsername = line.substring("USERNAME:".length()).trim();
                } else if (line.startsWith("PASSWORD:")) {
                    filePassword = line.substring("PASSWORD:".length()).trim();
                } else if (line.startsWith("ROLE:")) {
                    fileRole = line.substring("ROLE:".length()).trim();
                } else if (line.startsWith("----------------------------")) {
                    if (fileUsername != null && filePassword != null && fileRole != null) {
                        if (fileUsername.equals(username) && filePassword.equals(password)) {
                            return fileRole;
                        }
                    }
                    fileUsername = null;
                    filePassword = null;
                    fileRole = null;
                }
            }

            
            if (fileUsername != null && filePassword != null && fileRole != null) {
                if (fileUsername.equals(username) && filePassword.equals(password)) {
                    return fileRole;
                }
            }

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error: user_credentials.txt not found. Place it in the main project folder.", "File Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading user database: " + e.getMessage(), "File Read Error", JOptionPane.ERROR_MESSAGE);
        }

        return null; // Not found
    }

    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUsn = new javax.swing.JTextField();
        lblUsn = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pwPW = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setForeground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        txtUsn.setBackground(new java.awt.Color(204, 204, 204));
        txtUsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsnActionPerformed(evt);
            }
        });

        lblUsn.setBackground(new java.awt.Color(204, 204, 204));
        lblUsn.setText("Username:");

        lblPW.setBackground(new java.awt.Color(204, 204, 204));
        lblPW.setText("Password:");

        btnSignIn.setBackground(new java.awt.Color(0, 153, 204));
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign In");
        btnSignIn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 204));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pwPW.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("guest");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 153, 204));
        title.setText("Lipad Bantay Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPW, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsn)
                                    .addComponent(pwPW, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(title))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel1)))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnSignIn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(title)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsn)
                    .addComponent(txtUsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPW, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnSignIn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void writeLoginLog(String username, String role) {
        try {
            // Path to the log file
            String logFilePath = Paths.get(System.getProperty("user.dir"), 
                    "src", "main", "java", "com", "mycompany", 
                    "lipadbantayoopdsa", "Logs", "logs.txt").toString();

            // Get current timestamp
            String timestamp = java.time.LocalDateTime.now()
                    .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd | HH:mm:ss"));

            // Build log entry
            String logEntry = String.format(
                "[%s]%nEVENT  : LOGIN%nACTION : User Logged In%nACTOR  : %s%nROLE   : %s%n%n----------------------------------------%n%n",
                timestamp, username, role
            );

            // Write to file (append mode)
            try (PrintWriter writer = new PrintWriter(new FileWriter(logFilePath, true))) {
                writer.println(logEntry);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing login log: " + e.getMessage(), "Log Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void txtUsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsnActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        String username = txtUsn.getText().trim();
        String password = String.valueOf(pwPW.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String userRole = authenticateUser(username, password); // read from user_credentials.txt

        if (userRole != null) {
            
            // Log the user who signed in
            writeLoginLog(username, userRole);
            
            JFrame dashboard = null;
            switch (userRole) {
                case "ADMIN":
                    dashboard = new MainFlightDisplayAdmin();
                    break;
                case "AIRLINE_MANAGER":
                    dashboard = new AirlineManagerDashboard(username);
                    break;
                case "USER":
                    dashboard = new UserDashboard(username);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Unknown user role.", "Login Error", JOptionPane.ERROR_MESSAGE);
                    return;
            }

            dashboard.setVisible(true);
            this.dispose(); // close login form
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AuthenticationForm().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       MainFlightDisplayGuest displayGuest = new MainFlightDisplayGuest();
       displayGuest.setVisible(true);
       dispose();
       JOptionPane.showMessageDialog(this, "Guests are only limited to viewing Flights");
       
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblUsn;
    private javax.swing.JPasswordField pwPW;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtUsn;
    // End of variables declaration//GEN-END:variables
}
