/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa.popupInterface;

/**
 *
 * @author Joshua
 */
public class addFlightScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addFlightScreen.class.getName());

    /**
     * Creates new form addFlightScreen
     */
    public addFlightScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyContainer = new javax.swing.JPanel();
        topContainer = new javax.swing.JPanel();
        fucntionTitle = new javax.swing.JLabel();
        ARILINECODE = new javax.swing.JLabel();
        airlineField = new javax.swing.JTextField();
        AIRCRAFT = new javax.swing.JLabel();
        btn_addFlight = new javax.swing.JButton();
        ORIGIN = new javax.swing.JLabel();
        DESTINATION = new javax.swing.JLabel();
        origin_drpdwn = new javax.swing.JComboBox<>();
        destination_drpdwn = new javax.swing.JComboBox<>();
        ac_drpdwn = new javax.swing.JComboBox<>();
        FREQUENCY = new javax.swing.JLabel();
        M_check = new javax.swing.JCheckBox();
        TU_check = new javax.swing.JCheckBox();
        W_check = new javax.swing.JCheckBox();
        TH_check = new javax.swing.JCheckBox();
        F_check = new javax.swing.JCheckBox();
        ST_check = new javax.swing.JCheckBox();
        E_check = new javax.swing.JCheckBox();
        SU_check = new javax.swing.JCheckBox();
        TIME = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        FLNO = new javax.swing.JLabel();
        flnField = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodyContainer.setBackground(new java.awt.Color(255, 255, 255));

        topContainer.setBackground(new java.awt.Color(0, 153, 255));

        fucntionTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fucntionTitle.setText("ADD FLIGHT");

        javax.swing.GroupLayout topContainerLayout = new javax.swing.GroupLayout(topContainer);
        topContainer.setLayout(topContainerLayout);
        topContainerLayout.setHorizontalGroup(
            topContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topContainerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fucntionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topContainerLayout.setVerticalGroup(
            topContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fucntionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        ARILINECODE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ARILINECODE.setText("AIRLINE NAME");

        airlineField.setText("ICAO CODE");

        AIRCRAFT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AIRCRAFT.setText("AIRCRAFT");

        btn_addFlight.setText("ADD FLIGHT");

        ORIGIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ORIGIN.setText("ORIGIN");

        DESTINATION.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DESTINATION.setText("DESTINATION");

        origin_drpdwn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        destination_drpdwn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ac_drpdwn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FREQUENCY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FREQUENCY.setText("Frequency");

        M_check.setText("MONDAY");
        M_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_checkActionPerformed(evt);
            }
        });

        TU_check.setText("TUESDAY");

        W_check.setText("WEDNESDAY");

        TH_check.setText("THURSDAY");

        F_check.setText("FRIDAY");

        ST_check.setText("SATURDAY");

        E_check.setText("EVERYDAY");

        SU_check.setText("SUNDAY");
        SU_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SU_checkActionPerformed(evt);
            }
        });

        TIME.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TIME.setText("TIME");

        timeField.setText("0000z (Format)");

        FLNO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FLNO.setText("FLT NO.");

        flnField.setText("6767");

        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyContainerLayout = new javax.swing.GroupLayout(bodyContainer);
        bodyContainer.setLayout(bodyContainerLayout);
        bodyContainerLayout.setHorizontalGroup(
            bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyContainerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyContainerLayout.createSequentialGroup()
                        .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyContainerLayout.createSequentialGroup()
                                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ARILINECODE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(airlineField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AIRCRAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ac_drpdwn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bodyContainerLayout.createSequentialGroup()
                                .addComponent(origin_drpdwn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(destination_drpdwn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(bodyContainerLayout.createSequentialGroup()
                        .addComponent(ORIGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(DESTINATION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TIME, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FLNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(flnField)
                        .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(bodyContainerLayout.createSequentialGroup()
                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyContainerLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M_check)
                            .addComponent(TH_check))
                        .addGap(34, 34, 34)
                        .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyContainerLayout.createSequentialGroup()
                                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(F_check)
                                    .addComponent(TU_check)
                                    .addComponent(SU_check))
                                .addGap(40, 40, 40)
                                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(W_check)
                                    .addComponent(ST_check)))
                            .addComponent(FREQUENCY, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_check)))
                    .addGroup(bodyContainerLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btn_addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyContainerLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyContainerLayout.setVerticalGroup(
            bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyContainerLayout.createSequentialGroup()
                .addComponent(topContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyContainerLayout.createSequentialGroup()
                        .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(bodyContainerLayout.createSequentialGroup()
                                .addComponent(AIRCRAFT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac_drpdwn))
                            .addGroup(bodyContainerLayout.createSequentialGroup()
                                .addComponent(ARILINECODE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(airlineField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DESTINATION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ORIGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(origin_drpdwn)
                            .addComponent(destination_drpdwn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bodyContainerLayout.createSequentialGroup()
                        .addComponent(FLNO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flnField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(FREQUENCY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_check)
                    .addComponent(TU_check)
                    .addComponent(W_check))
                .addGap(18, 18, 18)
                .addGroup(bodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TH_check)
                    .addComponent(F_check)
                    .addComponent(ST_check))
                .addGap(18, 18, 18)
                .addComponent(SU_check)
                .addGap(18, 18, 18)
                .addComponent(E_check)
                .addGap(27, 27, 27)
                .addComponent(btn_addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_back)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void M_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_checkActionPerformed

    private void SU_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SU_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SU_checkActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addFlightScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AIRCRAFT;
    private javax.swing.JLabel ARILINECODE;
    private javax.swing.JLabel DESTINATION;
    private javax.swing.JCheckBox E_check;
    private javax.swing.JLabel FLNO;
    private javax.swing.JLabel FREQUENCY;
    private javax.swing.JCheckBox F_check;
    private javax.swing.JCheckBox M_check;
    private javax.swing.JLabel ORIGIN;
    private javax.swing.JCheckBox ST_check;
    private javax.swing.JCheckBox SU_check;
    private javax.swing.JCheckBox TH_check;
    private javax.swing.JLabel TIME;
    private javax.swing.JCheckBox TU_check;
    private javax.swing.JCheckBox W_check;
    private javax.swing.JComboBox<String> ac_drpdwn;
    private javax.swing.JTextField airlineField;
    private javax.swing.JPanel bodyContainer;
    private javax.swing.JButton btn_addFlight;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> destination_drpdwn;
    private javax.swing.JTextField flnField;
    private javax.swing.JLabel fucntionTitle;
    private javax.swing.JComboBox<String> origin_drpdwn;
    private javax.swing.JTextField timeField;
    private javax.swing.JPanel topContainer;
    // End of variables declaration//GEN-END:variables
}
