/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa.popupInterface;

import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.Database.Timetable.SortingFunction;
import com.mycompany.lipadbantayoopdsa.Database.Timetable.SortingFunctionA;
import com.mycompany.lipadbantayoopdsa.userAuthentication.LoginForm;
import com.mycompany.lipadbantayoopdsa.ArrivalTimetableGenerator;
import com.mycompany.lipadbantayoopdsa.MainFlightDisplayAdmin;
import com.mycompany.lipadbantayoopdsa.distanceCalculator;
import java.awt.Color;
import java.awt.Component;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Joshua
 */
public class archiveScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(archiveScreen.class.getName());

    /**
     * Creates new form archiveScreen
     */
    public archiveScreen() {
        initComponents();
        intializeComboBoxes();
        loadArchiveData(); // Load the archive file on startup
    }

    /**
     * This method is called from within the constructor to initisalize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopContainer = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SearchContainer = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        Combo_Status = new javax.swing.JComboBox<>();
        Combo_Airline = new javax.swing.JComboBox<>();
        Combo_Aircraft = new javax.swing.JComboBox<>();
        Combo_Origin = new javax.swing.JComboBox<>();
        Combo_Destination = new javax.swing.JComboBox<>();
        applyFilters = new javax.swing.JButton();
        resetFilters = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();
        BottomContainer = new javax.swing.JPanel();
        deleteFlight = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();
        unarchive = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TopContainer.setBackground(new java.awt.Color(51, 51, 51));

        Title.setFont(new java.awt.Font("Santana-Black", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("ARCHIVE");

        SearchContainer.setBackground(new java.awt.Color(102, 102, 102));

        SearchField.setText("Search for a flight");
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
        });
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(102, 102, 102));
        SearchButton.setText("Search");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchContainerLayout = new javax.swing.GroupLayout(SearchContainer);
        SearchContainer.setLayout(SearchContainerLayout);
        SearchContainerLayout.setHorizontalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        SearchContainerLayout.setVerticalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TopContainerLayout = new javax.swing.GroupLayout(TopContainer);
        TopContainer.setLayout(TopContainerLayout);
        TopContainerLayout.setHorizontalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TopContainerLayout.setVerticalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Combo_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combo_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_StatusActionPerformed(evt);
            }
        });

        Combo_Airline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Aircraft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        applyFilters.setText("Apply");
        applyFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFiltersActionPerformed(evt);
            }
        });

        resetFilters.setText("Reset Filters");
        resetFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFiltersActionPerformed(evt);
            }
        });

        FlightTable.setBackground(new java.awt.Color(255, 255, 255));
        FlightTable.setForeground(new java.awt.Color(0, 102, 204));
        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Status", "Airline", "Aircraft", "Origin", "Destination", "Frequency", "ETD", "ETA", "Flight Number", "Duration", "Distance", "Pax", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(FlightTable);

        BottomContainer.setBackground(new java.awt.Color(255, 255, 255));

        deleteFlight.setBackground(new java.awt.Color(255, 102, 102));
        deleteFlight.setText("DELETE");
        deleteFlight.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        deleteFlight.setBorderPainted(false);
        deleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFlightActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        unarchive.setBackground(new java.awt.Color(153, 255, 153));
        unarchive.setText("UNARCHIVE");
        unarchive.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        unarchive.setBorderPainted(false);
        unarchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unarchiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BottomContainerLayout = new javax.swing.GroupLayout(BottomContainer);
        BottomContainer.setLayout(BottomContainerLayout);
        BottomContainerLayout.setHorizontalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomContainerLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(unarchive, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BottomContainerLayout.setVerticalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomContainerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unarchive, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BottomContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Airline, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Aircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Origin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_Airline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Aircraft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetFilters)
                    .addComponent(applyFilters))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void intializeComboBoxes() {

        // Flight Status;
        Combo_Status.removeAllItems();
        Combo_Status.addItem("N/A");
        Combo_Status.addItem("Scheduled");
        Combo_Status.addItem("Delayed");
        Combo_Status.addItem("Canceled");

        //Airline
        Combo_Airline.removeAllItems();
        Combo_Airline.addItem("N/A");
        try {
            File airlineMaster = new File(AdminOperations.Database_Airlines_Path);
            Scanner airlineReader = new Scanner(airlineMaster);
            // adds options for the combobox, reads from the ac database
            while (airlineReader.hasNextLine()) {
                String arilineStringLine = airlineReader.nextLine();
                String arilineStringLineArray[] = arilineStringLine.split("-");
                Combo_Airline.addItem(arilineStringLineArray[0]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }

        //Aircraft
        Combo_Aircraft.removeAllItems();
        Combo_Aircraft.addItem("N/A");
        try {
            File aircraftMaster = new File(AdminOperations.Database_Aircarfts_Path);
            Scanner aircraftReader = new Scanner(aircraftMaster);
            // adds options for the combobox, reads from the ac database
            while (aircraftReader.hasNextLine()) {
                String aircraftStringLine = aircraftReader.nextLine();
                String aircraftStringLineArray[] = aircraftStringLine.split("-");
                Combo_Aircraft.addItem(aircraftStringLineArray[0]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }

        //Origin
        Combo_Origin.removeAllItems();
        Combo_Origin.addItem("N/A");
        try {
            File originMaster = new File(AdminOperations.Database_Aiports_Path);
            Scanner originReader = new Scanner(originMaster);
            // adds options for the combobox, reads from the ac database
            while (originReader.hasNextLine()) {
                String originStringLine = originReader.nextLine();
                String originStringLineArray[] = originStringLine.split("-");
                Combo_Origin.addItem(originStringLineArray[1]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }

        //Destination 
        Combo_Destination.removeAllItems();
        Combo_Destination.addItem("N/A");
        try {
            File destinationMaster = new File(AdminOperations.Database_Aiports_Path);
            Scanner destiantionReader = new Scanner(destinationMaster);
            // adds options for the combobox, reads from the ac database
            while (destiantionReader.hasNextLine()) {
                String destinationStringLine = destiantionReader.nextLine();
                String destinationStringLineArray[] = destinationStringLine.split("-");
                Combo_Destination.addItem(destinationStringLineArray[1]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }

    }
    
    public void loadArchiveData() {
        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);
        // Admin empty row
        model.addRow(new String[]{"", "", "", "", "", "", "", "", "", "", "", "", ""});

        File file = new File(AdminOperations.Database_TimeTable_Archive_Path);

        // Create file if not exists to prevent crash
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException e) {
            }
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");
                    if (rowData.length >= 10) {
                        // Re-use your existing logic to calculate distances/ETA
                        processAndAddSearchRow(model, rowData);
                    }
                }
            }
        } catch (IOException e) {
            logger.log(Level.SEVERE, "Error loading archive", e);
        }
    }
    
    
    public void applyFilters() {
        String[] filesToFilter = {
            AdminOperations.Database_TimeTable_Archive_Path
        };

        String searchTerm = SearchField.getText().trim().toLowerCase();
        String placeholder = "search for a flight".toLowerCase();

        String selStatus = Combo_Status.getSelectedItem().toString();
        String selAirline = Combo_Airline.getSelectedItem().toString();
        String selAircraft = Combo_Aircraft.getSelectedItem().toString();
        String selOrigin = Combo_Origin.getSelectedItem().toString();
        String selDest = Combo_Destination.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);

        // Admin requirement: Empty first row
        model.addRow(new String[]{"", "", "", "", "", "", "", "", "", "", "", "", ""});

        for (String filePath : filesToFilter) {
            File file = new File(filePath);
            if (!file.exists()) {
                continue;
            }

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) {
                        continue;
                    }

                    String[] rowData = line.split("-");
                    if (rowData.length < 10) {
                        continue;
                    }

                    // Match checks
                    boolean matchesSearch = searchTerm.equals(placeholder) || searchTerm.isEmpty() || line.toLowerCase().contains(searchTerm);
                    boolean matchesStatus = selStatus.equals("N/A") || rowData[9].equalsIgnoreCase(selStatus);
                    boolean matchesAirline = selAirline.equals("N/A") || rowData[0].equalsIgnoreCase(selAirline);
                    boolean matchesAircraft = selAircraft.equals("N/A") || rowData[1].equalsIgnoreCase(selAircraft);

                    // Flexible matching for Origin/Dest
                    boolean matchesOrigin = selOrigin.equals("N/A") || rowData[2].toLowerCase().contains(selOrigin.toLowerCase());
                    boolean matchesDest = selDest.equals("N/A") || rowData[3].toLowerCase().contains(selDest.toLowerCase());

                    if (matchesSearch && matchesStatus && matchesAirline && matchesAircraft && matchesOrigin && matchesDest) {
                        processAndAddSearchRow(model, rowData);
                    }
                }
            } catch (IOException e) {
                logger.log(Level.SEVERE, "Filter error on " + filePath, e);
            }
        }
    }
    
    
    public void processAndAddSearchRow(DefaultTableModel model, String[] rowData) {
        try {
            String airline = rowData[0];
            String aircraft = rowData[1];
            String origin = rowData[2];
            String destination = rowData[3];
            String freq = rowData[4];
            String ETD = rowData[5];
            String flightNo = rowData[6];
            String flightPax = rowData[7];
            String flightCargo = rowData[8];
            String flightStatus = rowData[9];

            distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

            // Calculate Distance and Duration
            double distVal = calc.calculateDistanceKm();
            String distanceStr = String.format("%.0f km", distVal);

            int totalMinutes = calc.calculateFlightDurationMinutes();
            String durationStr = (totalMinutes / 60) + "h " + (totalMinutes % 60) + "m";

            // ETA Math (1230 -> 12:30 + Duration)
            int etdHours = Integer.parseInt(ETD.substring(0, 2));
            int etdMins = Integer.parseInt(ETD.substring(2, 4));
            int arrivalTotalMins = (etdHours * 60) + etdMins + totalMinutes;
            String ETA = String.format("%02d%02d", (arrivalTotalMins / 60) % 24, arrivalTotalMins % 60);

            model.addRow(new Object[]{
                flightStatus, airline, aircraft, origin, destination,
                freq, ETD, ETA, flightNo, durationStr, distanceStr, flightPax, flightCargo
            });

            applyTableStyle(flightStatus);
        } catch (Exception e) {
            // Skip malformed rows safely
        }
    }
    
    
    private void applyTableStyle(String flightStatus) {
        DefaultTableCellRenderer statusRowRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                
                if (isSelected) {
                    c.setBackground(table.getSelectionBackground());
                    c.setForeground(table.getSelectionForeground());
                    return c;
                }

                String status = table.getValueAt(row, 0).toString();

                if (status.equals("Scheduled")) {
                    c.setBackground(new Color(200, 255, 200));
                    c.setForeground(Color.BLACK);
                } else if (status.equals("Delayed")) {
                    c.setBackground(new Color(255, 213, 128));
                    c.setForeground(Color.BLACK);
                } else if (status.equals("Canceled")) {
                    c.setBackground(new Color(255, 128, 128));
                    c.setForeground(Color.BLACK);
                } else {
                    c.setBackground(table.getBackground());
                    c.setForeground(table.getForeground());
                }

                return c;
            }
        };

        for (int i = 0; i < FlightTable.getColumnCount(); i++) {
            FlightTable.getColumnModel().getColumn(i).setCellRenderer(statusRowRenderer);
        }
    }
    
    
    
    
    public void searchFlights() {
        String searchTerm = SearchField.getText().trim().toLowerCase();
        String placeholderText = "search for a flight".toLowerCase();

        if (searchTerm.equals(placeholderText) || searchTerm.isEmpty()) {
            loadArchiveData();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);
        model.addRow(new String[]{"", "", "", "", "", "", "", "", "", "", "", "", ""});

        String[] filesToSearch = {
            AdminOperations.Database_TimeTable_Archive_Path
        };

        for (String filePath : filesToSearch) {
            File file = new File(filePath);
            if (!file.exists()) {
                continue;
            }

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) {
                        continue;
                    }
                    String[] rowData = line.split("-");

                    boolean match = false;
                    for (String data : rowData) {
                        if (data.trim().toLowerCase().contains(searchTerm)) {
                            match = true;
                            break;
                        }
                    }

                    if (match && rowData.length >= 10) {
                        processAndAddSearchRow(model, rowData);
                    }
                }
            } catch (IOException e) {
                System.out.println("Error reading file: " + filePath);
            }
        }
    }
    
    
    
    
    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        // if search text field is clicked then remove the palceholder text
        SearchField.setText("");
        SearchField.setForeground(Color.BLACK);
    }//GEN-LAST:event_SearchFieldFocusGained

    
    
    private void resetSearchField() {
        SearchField.setText("Search for a flight");
        SearchField.setForeground(Color.LIGHT_GRAY);
    }
    
    
    
    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        if (SearchField.getText().trim().isEmpty()) {
            resetSearchField();
        }
    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // if enter is pressed then search function
        searchFlights();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // same procces for the textfield but in a button form
        searchFlights();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void Combo_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_StatusActionPerformed

    }//GEN-LAST:event_Combo_StatusActionPerformed

    private void applyFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFiltersActionPerformed
        applyFilters();
    }//GEN-LAST:event_applyFiltersActionPerformed

    private void resetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFiltersActionPerformed
        Combo_Aircraft.setSelectedIndex(0);
        Combo_Airline.setSelectedIndex(0);
        Combo_Destination.setSelectedIndex(0);
        Combo_Origin.setSelectedIndex(0);
        Combo_Status.setSelectedIndex(0);
        applyFilters();
    }//GEN-LAST:event_resetFiltersActionPerformed

    private void deleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFlightActionPerformed
            // PERMANENT DELETE BUTTON
            int selectedRow = FlightTable.getSelectedRow();

            if (selectedRow == -1 || selectedRow == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Select a flight to permanently delete.");
                return;
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure? This will PERMANENTLY delete the record.", "Delete Forever",
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                String flightNum = FlightTable.getValueAt(selectedRow, 8).toString();
                try {
                    // Delete from Archive File
                    deleteLineFromFile(AdminOperations.Database_TimeTable_Archive_Path, flightNum);
                    loadArchiveData(); // Refresh table
                    javax.swing.JOptionPane.showMessageDialog(this, "Flight deleted permanently.");
                } catch (IOException e) {
                    System.out.println("Error deleting: " + e.getMessage());
                }
            }
        }
    
    // Helper to move string from Archive -> Departure
    private void restoreLineToMain(String flightNum) throws IOException {
        File archiveFile = new File(AdminOperations.Database_TimeTable_Archive_Path);
        File departureFile = new File(AdminOperations.Database_TimeTable_Departure_Path);

        try (Scanner scanner = new Scanner(archiveFile); BufferedWriter writer = new BufferedWriter(new FileWriter(departureFile, true))) { // true = append

            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] parts = line.split("-");
                // Check flight number at index 6
                if (parts.length > 6 && parts[6].equalsIgnoreCase(flightNum)) {
                    writer.write(line);
                    writer.newLine();
                    break; // Found it, stop searching
                }
            }
        }
    }

    // Helper to delete line from specific file
    private void deleteLineFromFile(String filePath, String flightNumberToRemove) throws IOException {
        File inputFile = new File(filePath);
        File tempFile = new File(inputFile.getParent(), "temp_archive_" + inputFile.getName());

        if (!inputFile.exists()) {
            return;
        }

        try (BufferedReader reader = new BufferedReader(new FileReader(inputFile)); BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split("-");
                if (parts.length > 6 && parts[6].equalsIgnoreCase(flightNumberToRemove)) {
                    continue; // Skip writing this line
                }
                writer.write(line);
                writer.newLine();
            }
        }

        if (inputFile.delete()) {
            tempFile.renameTo(inputFile);
        }
    }//GEN-LAST:event_deleteFlightActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MainFlightDisplayAdmin mainDisplay = new MainFlightDisplayAdmin();
        mainDisplay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void unarchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unarchiveActionPerformed
        // UNARCHIVE BUTTON (Restore to Main Database)
        int selectedRow = FlightTable.getSelectedRow();

        if (selectedRow == -1 || selectedRow == 0) { // Check 0 to skip empty admin row
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a flight to restore.");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Restore this flight to the Active Schedule?", "Confirm Unarchive",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String flightNum = FlightTable.getValueAt(selectedRow, 8).toString();

            try {
                // A. Find line in Archive and Write to Departure Master
                restoreLineToMain(flightNum);

                // B. Delete from Archive
                deleteLineFromFile(AdminOperations.Database_TimeTable_Archive_Path, flightNum);

                // C. Regenerate Arrivals (since we just added a departure)
                ArrivalTimetableGenerator.generate();

                // D. Refresh View
                loadArchiveData();
                javax.swing.JOptionPane.showMessageDialog(this, "Flight restored successfully.");

            } catch (IOException e) {
                System.out.println("Error restoring flight: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_unarchiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new archiveScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomContainer;
    private javax.swing.JComboBox<String> Combo_Aircraft;
    private javax.swing.JComboBox<String> Combo_Airline;
    private javax.swing.JComboBox<String> Combo_Destination;
    private javax.swing.JComboBox<String> Combo_Origin;
    private javax.swing.JComboBox<String> Combo_Status;
    private javax.swing.JTable FlightTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchContainer;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopContainer;
    private javax.swing.JButton applyFilters;
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton deleteFlight;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetFilters;
    private javax.swing.JToggleButton unarchive;
    // End of variables declaration//GEN-END:variables
}
