package com.mycompany.lipadbantayoopdsa.superAdmin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jedrich
 */
public class AccountApproval extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccountApproval.class.getName());
    private static final String USER_CREDS_PATH = "src/main/java/com/mycompany/lipadbantayoopdsa/userAuthentication/user_credentials.txt";
    private static final String AIRLINES_DB_PATH = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Airlines/";
    private static final String ROUTES_DB_PATH = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Routes/";
    private static final String AIRLINES_MASTER_PATH = AIRLINES_DB_PATH + "Airlines_Master.txt";
    private static final String SEPARATOR = "----------------------------";
    /**
     * Creates new form AccountApproval
     */
    public AccountApproval() {
        initComponents();
        loadPendingRequests();
    }
    private void loadPendingRequests() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        try (BufferedReader br = new BufferedReader(new FileReader(USER_CREDS_PATH))) {
            String line;
            String name = "", airline = "", username = "", prefix = "", role = "", status = "";

            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.equals(SEPARATOR)) {
                    // Check for pending Airline Manager accounts
                    if ("AIRLINE_MANAGER".equals(role) && "PENDING".equals(status)) {
                        model.addRow(new Object[]{name, airline, username, prefix, status});
                    }
                    // Reset for next block
                    name = ""; airline = ""; username = ""; prefix = ""; role = ""; status = "";
                } else if (line.contains(": ")) {
                    String[] parts = line.split(": ", 2);
                    String key = parts[0].trim();
                    String value = parts[1].trim();

                    switch (key) {
                        case "MANAGER": name = value; break;
                        case "AIRLINE": airline = value; break;
                        case "USERNAME": username = value; break;
                        case "PREFIX": prefix = value; break;
                        case "ROLE": role = value; break;
                        case "STATUS": status = value; break;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }
    private boolean updateUserStatus(String targetUsername, String newStatus) {
        File inputFile = new File(USER_CREDS_PATH);
        File tempFile = new File(USER_CREDS_PATH + ".tmp");

        try (BufferedReader br = new BufferedReader(new FileReader(inputFile));
             BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            StringBuilder blockBuffer = new StringBuilder();
            boolean isMatch = false;

            while ((line = br.readLine()) != null) {
                blockBuffer.append(line).append("\n");
                if (line.trim().equals("USERNAME: " + targetUsername)) isMatch = true;

                if (line.trim().equals(SEPARATOR)) {
                    String blockStr = blockBuffer.toString();
                    if (isMatch) {
                        blockStr = blockStr.replaceAll("STATUS: .*", "STATUS: " + newStatus);
                    }
                    bw.write(blockStr);
                    blockBuffer.setLength(0);
                    isMatch = false;
                }
            }
        } catch (IOException e) {
            return false;
        }
        
        if (inputFile.delete()) return tempFile.renameTo(inputFile);
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Manager Name", "Airline", "Username", "Prefix", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        button3.setBackground(new java.awt.Color(51, 204, 0));
        button3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setLabel("Approve Selected");
        button3.addActionListener(this::button3ActionPerformed);

        button4.setBackground(new java.awt.Color(255, 0, 51));
        button4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setLabel("Reject Selected");
        button4.addActionListener(this::button4ActionPerformed);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );

        button1.setLabel("Back to Dashboard");
        button1.addActionListener(this::button1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select an account to approve.");
            return;
        }

        String managerName = jTable1.getValueAt(row, 0).toString();
        String airlineName = jTable1.getValueAt(row, 1).toString().toUpperCase(); // ALL CAPS
        String username = jTable1.getValueAt(row, 2).toString();
        String prefix = jTable1.getValueAt(row, 3).toString();

        if (updateUserStatus(username, "ACTIVE")) {
           
            try {
                new File(AIRLINES_DB_PATH).mkdirs(); 
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(AIRLINES_MASTER_PATH, true))) {
                    bw.write(airlineName + "-" + prefix + "-1.00");
                    bw.newLine();
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Master List Error: " + e.getMessage());
            }

            
            try {
                new File(ROUTES_DB_PATH).mkdirs(); 
                String routesFile = ROUTES_DB_PATH + "Routes_" + airlineName + ".txt";
                File f = new File(routesFile);
                if (!f.exists()) f.createNewFile();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Routes File Error: " + e.getMessage());
            }

            JOptionPane.showMessageDialog(this, airlineName + " Approved successfully!");
            loadPendingRequests(); 
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:this.dispose();
        this.dispose();
        new SuperAdmin().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            String username = jTable1.getValueAt(row, 2).toString();
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to REJECT this account?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                if (updateUserStatus(username, "REJECTED")) {
                    loadPendingRequests();
                }
            }
        }
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccountApproval().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
