/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa;

import com.mycompany.lipadbantayoopdsa.popupInterface.addFlightScreen;
import com.mycompany.lipadbantayoopdsa.popupInterface.editFlightScreen_1;
import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.Database.Timetable.SortingFunction;
import com.mycompany.lipadbantayoopdsa.Database.Timetable.SortingFunctionA;
import com.mycompany.lipadbantayoopdsa.userAuthentication.AirlineManagerDashboard;
import com.mycompany.lipadbantayoopdsa.popupInterface.addFlightScreen_M;
import com.mycompany.lipadbantayoopdsa.userAuthentication.LoginForm;
import com.mycompany.lipadbantayoopdsa.popupInterface.editFlightScreen_M;
import java.awt.Color;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Joshua
 */
public class MainFlightDisplayManagers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFlightDisplayManagers.class.getName());
    
    private int selectedRow = -1;

    private String currentAirlineName;
    private String currentAirlinePrefix;
    /**
     * Creates new form MainFlightDisplay
     */
    public MainFlightDisplayManagers() {
        initComponents();
        loadFlightsToTableDeparture();
        ArrivalTimetableGenerator.generate();
    }
    
   
    
     public MainFlightDisplayManagers(String Airlinename, String Prefix) {
        initComponents();
        // overload consteructor for the airline manager since it will get the flno prefix and the airline name 
        this.currentAirlineName = Airlinename;
        this.currentAirlinePrefix = Prefix;
        
        Title.setText("LIPAD BANTAY (" + Airlinename.toUpperCase() + ")");

        loadFlightsToTableDeparture();
        ArrivalTimetableGenerator.generate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        TopContainer = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SearchContainer = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        BottomContainer = new javax.swing.JPanel();
        addFlight = new javax.swing.JToggleButton();
        Arrival = new javax.swing.JToggleButton();
        Departures = new javax.swing.JToggleButton();
        deleteFlight = new javax.swing.JToggleButton();
        editFlight = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(255, 255, 255));

        TopContainer.setBackground(new java.awt.Color(51, 153, 255));

        Title.setFont(new java.awt.Font("Santana-Black", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("LIPAD BANTAY");

        SearchContainer.setBackground(new java.awt.Color(255, 255, 255));

        SearchField.setText("Search for a flight");
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
        });
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(0, 102, 255));
        SearchButton.setText("Search");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchContainerLayout = new javax.swing.GroupLayout(SearchContainer);
        SearchContainer.setLayout(SearchContainerLayout);
        SearchContainerLayout.setHorizontalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        SearchContainerLayout.setVerticalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TopContainerLayout = new javax.swing.GroupLayout(TopContainer);
        TopContainer.setLayout(TopContainerLayout);
        TopContainerLayout.setHorizontalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TopContainerLayout.setVerticalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BottomContainer.setBackground(new java.awt.Color(255, 255, 255));

        addFlight.setBackground(new java.awt.Color(204, 255, 204));
        addFlight.setText("ADD");
        addFlight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightActionPerformed(evt);
            }
        });

        Arrival.setBackground(new java.awt.Color(0, 153, 255));
        Arrival.setForeground(new java.awt.Color(255, 255, 255));
        Arrival.setText("Arrival");
        Arrival.setBorder(null);
        Arrival.setMaximumSize(new java.awt.Dimension(120, 35));
        Arrival.setMinimumSize(new java.awt.Dimension(120, 35));
        Arrival.setPreferredSize(new java.awt.Dimension(120, 35));
        Arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrivalActionPerformed(evt);
            }
        });

        Departures.setBackground(new java.awt.Color(0, 153, 255));
        Departures.setForeground(new java.awt.Color(255, 255, 255));
        Departures.setText("Departure");
        Departures.setBorder(null);
        Departures.setMaximumSize(new java.awt.Dimension(120, 35));
        Departures.setMinimumSize(new java.awt.Dimension(120, 35));
        Departures.setPreferredSize(new java.awt.Dimension(120, 35));
        Departures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeparturesActionPerformed(evt);
            }
        });

        deleteFlight.setBackground(new java.awt.Color(255, 102, 102));
        deleteFlight.setText("DELETE");
        deleteFlight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFlightActionPerformed(evt);
            }
        });

        editFlight.setBackground(new java.awt.Color(255, 153, 102));
        editFlight.setText("EDIT");
        editFlight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFlightActionPerformed(evt);
            }
        });

        jToggleButton1.setText("BACK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BottomContainerLayout = new javax.swing.GroupLayout(BottomContainer);
        BottomContainer.setLayout(BottomContainerLayout);
        BottomContainerLayout.setHorizontalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomContainerLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BottomContainerLayout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))
                    .addGroup(BottomContainerLayout.createSequentialGroup()
                        .addComponent(Arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Departures, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        BottomContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Arrival, Departures});

        BottomContainerLayout.setVerticalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomContainerLayout.createSequentialGroup()
                .addGroup(BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Departures, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        FlightTable.setBackground(new java.awt.Color(255, 255, 255));
        FlightTable.setForeground(new java.awt.Color(0, 102, 204));
        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ariline", "Aircraft", "Origin", "Destination", "Frequency", "Time", "Flight Number", "Duration", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(FlightTable);
        if (FlightTable.getColumnModel().getColumnCount() > 0) {
            FlightTable.getColumnModel().getColumn(0).setResizable(false);
            FlightTable.getColumnModel().getColumn(1).setResizable(false);
            FlightTable.getColumnModel().getColumn(2).setResizable(false);
            FlightTable.getColumnModel().getColumn(3).setResizable(false);
            FlightTable.getColumnModel().getColumn(4).setResizable(false);
            FlightTable.getColumnModel().getColumn(5).setResizable(false);
            FlightTable.getColumnModel().getColumn(6).setResizable(false);
            FlightTable.getColumnModel().getColumn(7).setResizable(false);
            FlightTable.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BottomContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(TopContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(BottomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    
    //------------------DEPARTURE TABLE------------------------------
    public void loadFlightsToTableDeparture() {
        
        SortingFunction.sortFile();
        SortingFunctionA.sortFile();
        FlightTable.revalidate();
        FlightTable.repaint();
        
        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        //INTIALIZE TABLE
        model.setRowCount(0);

        File file = new File(AdminOperations.Database_TimeTable_Departure_Path);
        
        //reads from file and then displays to Deparutre table
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;    

             

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                  
                    // skip if not from currentiarlines
                    if (currentAirlineName != null && !rowData[0].trim().equalsIgnoreCase(currentAirlineName)) {
                        continue; 
                    }
                  
                    String airline = rowData[0];
                    String aircraft = rowData[1];
                    String origin = rowData[2];
                    String destination = rowData[3];
                    String freq = rowData[4];
                    String time = rowData[5];
                    String flightNo = (rowData.length == 7) ? rowData[6] : "";

                    String distanceStr = "N/A";
                    String durationStr = "N/A";

                    try {
                        
                        distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

                        
                        double distVal = calc.calculateDistanceKm();
                        distanceStr = String.format("%.0f km", distVal);

                        
                        int totalMinutes = calc.calculateFlightDurationMinutes();
                        int hrs = totalMinutes / 60;
                        int mins = totalMinutes % 60;
                        durationStr = hrs + "h " + mins + "m";

                    } catch (Exception e) {
                       
                        System.out.println("Error in Calculating Time");
                    }
    
                    String[] adjustedRow = {
                        airline, aircraft, origin, destination, freq, time, flightNo, 
                        durationStr, distanceStr 
                    };
                    model.addRow(adjustedRow);
                    
                }
            }
            br.close();

        } catch (IOException e) {
            System.out.println("Error loading departures");
        }
    }
    //-----------------------------------------------------------------------

    //------------------ARRIVAL TABLE------------------------------
    public void loadFlightsToTableArrival() {
  
        SortingFunction.sortFile();
        SortingFunctionA.sortFile();
        FlightTable.revalidate();
        FlightTable.repaint();
        
        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        //INTIALIZE TABLE
        model.setRowCount(0);

        File file = new File(AdminOperations.Database_TimeTable_Arrivals_Path);

        //reads from file and then displays to Arrival table
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    
                    if (currentAirlineName != null && !rowData[0].trim().equalsIgnoreCase(currentAirlineName)) {
                        continue; 
                    }
                    

                  
                    String airline = rowData[0];
                    String aircraft = rowData[1];
                    String origin = rowData[2];
                    String destination = rowData[3];
                    String freq = rowData[4];
                    String time = rowData[5];
                    String flightNo = (rowData.length == 7) ? rowData[6] : "";

                    String distanceStr = "N/A";
                    String durationStr = "N/A";

               
                    try {
                        distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);
                        double distVal = calc.calculateDistanceKm();
                        distanceStr = String.format("%.0f km", distVal);

                        int totalMinutes = calc.calculateFlightDurationMinutes();
                        durationStr = (totalMinutes / 60) + "h " + (totalMinutes % 60) + "m";
                    } catch (Exception e) {}

                    
                    String[] adjustedRow = { 
                        airline, aircraft, origin, destination, freq, time, flightNo, 
                        durationStr, distanceStr 
                    };
                    model.addRow(adjustedRow);
                }
            }
            br.close();

        } catch (IOException e) {
            System.out.println("Error loading arrivals ");
        }
    }
    //-----------------------------------------------------------------------
    
    //------------------DEFAULT TABLE VIEW------------------------------
    private String getActiveTimetablePath() {
        if (Arrival.getBackground().equals(Color.WHITE)) {
            return AdminOperations.Database_TimeTable_Arrivals_Path;
        } else {       
            return AdminOperations.Database_TimeTable_Departure_Path;
        }
    }
     //-----------------------------------------------------------------------
    
    public void searchFlights() {
     
        String filePath = getActiveTimetablePath();
        File file = new File(filePath);

        
        String searchTerm = SearchField.getText().trim().toLowerCase();

   
        String placeholderText = "search for a flight".toLowerCase();

      
        if (searchTerm.equals(placeholderText) || searchTerm.isEmpty()) {
          
            if (Arrival.getBackground().equals(Color.WHITE)) {
                loadFlightsToTableArrival();
            } else {
                loadFlightsToTableDeparture();
            }
            return;
        }

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0); // Clear existing data

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    
                    if (currentAirlineName != null && !rowData[0].trim().equalsIgnoreCase(currentAirlineName)) {
                        continue; 
                    }
                   

                   
                    boolean match = false;
                    for (String data : rowData) {
                        if (data.trim().toLowerCase().contains(searchTerm)) {
                            match = true;
                            break;
                        }
                    }

                  
                    if (match) {
                        String distanceStr = "N/A";
                        String durationStr = "N/A";

                      
                        try {
                            distanceCalculator calc = new distanceCalculator(rowData[2], rowData[3], rowData[1]);
                            double distVal = calc.calculateDistanceKm();
                            distanceStr = String.format("%.0f km", distVal);
                            int totalMinutes = calc.calculateFlightDurationMinutes();
                            durationStr = (totalMinutes / 60) + "h " + (totalMinutes % 60) + "m";
                        } catch (Exception e) {
                        }

                        
                        String[] adjustedRow = {
                            rowData[0], rowData[1], rowData[2], rowData[3], rowData[4], rowData[5], rowData[6],
                            durationStr, distanceStr
                        };
                        model.addRow(adjustedRow);
                        
                    }
                }
            }
        } catch (IOException e) {
           
            System.out.println("Error reading flight file for search");
        }
    }
    
    private void resetSearchField() {
        SearchField.setText("Search for a flight");
        SearchField.setForeground(Color.LIGHT_GRAY);
    }
    
    private void ArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrivalActionPerformed
        Arrival.setBackground(Color.WHITE);
        Arrival.setForeground(Color.BLACK);
        Departures.setBackground(Color.getHSBColor(0.5833f, 0.8f, 1.0f));
        Departures.setForeground(Color.WHITE);
        
        FlightTable.getColumnModel().getColumn(5).setHeaderValue("ETA");
        FlightTable.getTableHeader().repaint();
        
        loadFlightsToTableArrival();
        
        resetSearchField();
    }//GEN-LAST:event_ArrivalActionPerformed

    private void DeparturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeparturesActionPerformed
        Departures.setBackground(Color.WHITE);
        Departures.setForeground(Color.BLACK);
        Arrival.setBackground(Color.getHSBColor(0.5833f, 0.8f, 1.0f));
        Arrival.setForeground(Color.WHITE);
        
        FlightTable.getColumnModel().getColumn(5).setHeaderValue("ETD");
        FlightTable.getTableHeader().repaint();
        
        loadFlightsToTableDeparture();
        
        resetSearchField();
    }//GEN-LAST:event_DeparturesActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        searchFlights();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        SearchField.setText("");
        SearchField.setForeground(Color.BLACK);
    }//GEN-LAST:event_SearchFieldFocusGained

    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        if (SearchField.getText().trim().isEmpty()) {
            SearchField.setText("Search for a flight");
            SearchField.setForeground(Color.LIGHT_GRAY);
        }   
    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
      searchFlights();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void addFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightActionPerformed
        addFlightScreen_M addPopUp = new addFlightScreen_M(currentAirlineName, currentAirlinePrefix);
    
        addPopUp.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (Arrival.getBackground().equals(Color.WHITE)) {
                    loadFlightsToTableArrival();
                } else {
                    loadFlightsToTableDeparture();
                }
            }
        });

        addPopUp.setVisible(true);
        
    }//GEN-LAST:event_addFlightActionPerformed

    private void editFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFlightActionPerformed
        
        selectedRow = FlightTable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a flight to edit.");
            return;
        }

     
        Object airlineValue = FlightTable.getValueAt(selectedRow, 0);
        String airline = (airlineValue != null) ? airlineValue.toString() : "";

    
        if (airline.equalsIgnoreCase("null") || airline.isEmpty()) {
            airline = this.currentAirlineName;
        }

        String aircraft = FlightTable.getValueAt(selectedRow, 1).toString();
        String origin = FlightTable.getValueAt(selectedRow, 2).toString();
        String destination = FlightTable.getValueAt(selectedRow, 3).toString();
        String frequency = FlightTable.getValueAt(selectedRow, 4).toString();
        String time = FlightTable.getValueAt(selectedRow, 5).toString();
        String flightNumber = FlightTable.getValueAt(selectedRow, 6).toString();

     
        editFlightScreen_M editPopUp = new editFlightScreen_M(
                airline, aircraft, origin, destination, frequency, time, flightNumber, currentAirlinePrefix
        );

       
        editPopUp.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (Arrival.getBackground().equals(java.awt.Color.WHITE)) {
                    loadFlightsToTableArrival();
                } else {
                    loadFlightsToTableDeparture();
                }
            }
        });

      
        editPopUp.setVisible(true);
    }//GEN-LAST:event_editFlightActionPerformed

    private void deleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFlightActionPerformed

        int selectedRow = FlightTable.getSelectedRow();


        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please select a flight to delete.",
                "No Selection",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }


        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to delete this flight from BOTH Departures and Arrivals?", 
            "Confirm Deletion", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );

       
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();

            
            String flightNumber = FlightTable.getValueAt(selectedRow, 6).toString();

            
            model.removeRow(selectedRow);

            
            try {
                
                deleteLineFromFile(AdminOperations.Database_TimeTable_Departure_Path, flightNumber);

                
                deleteLineFromFile(AdminOperations.Database_TimeTable_Arrivals_Path, flightNumber);

                javax.swing.JOptionPane.showMessageDialog(this, "Flight deleted successfully from database.");

            } catch (IOException e) {
                System.out.println("Error deleting flight from file: " + e.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this, "Error updating database file.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    
    private void deleteLineFromFile(String filePath, String flightNumberToRemove) throws IOException {
        File inputFile = new File(filePath);
        File tempFile = new File(inputFile.getParent(), "temp_deletion_" + inputFile.getName());

      
        if (!inputFile.exists()) {
            System.out.println("File not found: " + filePath);
            return;
        }

        try (Scanner reader = new Scanner(inputFile);
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            while (reader.hasNextLine()) {
                String line = reader.nextLine();

               
                if (!line.contains(flightNumberToRemove)) {
                    writer.write(line);
                    writer.newLine();
                }
            }
        }

        
        if (!inputFile.delete()) {
            if (!inputFile.delete()) {
                System.out.println("Could not delete original file: " + filePath);
                return;
            }
        }

        if (!tempFile.renameTo(inputFile)) {
            System.out.println("Could not rename temp file to: " + filePath);
        }
    }
    

    private void updateTimetableFile(String airline, String aircraft, String origin, String destination, String frequency, String time, String flightNumber) {
        String filePath = getActiveTimetablePath();
        File file = new File(filePath);

        try {
            
            BufferedReader reader = new BufferedReader(new FileReader(file));
            StringBuilder fileContent = new StringBuilder();
            String line;

           
            while ((line = reader.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    
                    String[] rowData = line.split("-");

                    
                    if (rowData.length == 7) {
                       if (rowData[0].equals(airline) && rowData[1].equals(aircraft) && rowData[2].equals(origin)
                            && rowData[3].equals(destination) && rowData[4].equals(frequency) && rowData[5].equals(time)
                            && rowData[6].equals(flightNumber)) {
                            continue;
                        }
                    }

                    fileContent.append(line).append(System.lineSeparator());
                }
            }

            reader.close();

          
            BufferedWriter writer = new BufferedWriter(new FileWriter(file));
            writer.write(fileContent.toString());
            writer.close();

        } catch (IOException e) {
            logger.log(Level.SEVERE, "Error updating flight file after deletion.", e);
        }
    }//GEN-LAST:event_deleteFlightActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        LoginForm display = new LoginForm();
        display.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFlightDisplayManagers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Arrival;
    private javax.swing.JPanel BottomContainer;
    private javax.swing.JPanel Container;
    private javax.swing.JToggleButton Departures;
    private javax.swing.JTable FlightTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchContainer;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopContainer;
    private javax.swing.JToggleButton addFlight;
    private javax.swing.JToggleButton deleteFlight;
    private javax.swing.JToggleButton editFlight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
