/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa;

import com.mycompany.lipadbantayoopdsa.popupInterface.addFlightScreen;
import com.mycompany.lipadbantayoopdsa.popupInterface.editFlightScreen_1;
import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.userAuthentication.LoginForm;
import java.awt.Color;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Joshua
 */
public class MainFlightDisplayGuest extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFlightDisplayGuest.class.getName());
    
    private int selectedRow = -1;

    /**
     * Creates new form MainFlightDisplay
     */
    public MainFlightDisplayGuest() {
        initComponents();
        loadFlightsToTableDeparture();
        ArrivalTimetableGenerator.generate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        TopContainer = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SearchContainer = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        BottomContainer = new javax.swing.JPanel();
        Arrival = new javax.swing.JToggleButton();
        Departures = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(204, 204, 204));

        TopContainer.setBackground(new java.awt.Color(102, 102, 102));

        Title.setFont(new java.awt.Font("Santana-Black", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("LIPAD BANTAY");

        SearchContainer.setBackground(new java.awt.Color(204, 204, 204));

        SearchField.setBackground(new java.awt.Color(204, 204, 204));
        SearchField.setForeground(new java.awt.Color(0, 0, 0));
        SearchField.setText("Search for a flight");
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
        });
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(102, 102, 102));
        SearchButton.setText("Search");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchContainerLayout = new javax.swing.GroupLayout(SearchContainer);
        SearchContainer.setLayout(SearchContainerLayout);
        SearchContainerLayout.setHorizontalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        SearchContainerLayout.setVerticalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TopContainerLayout = new javax.swing.GroupLayout(TopContainer);
        TopContainer.setLayout(TopContainerLayout);
        TopContainerLayout.setHorizontalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TopContainerLayout.setVerticalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BottomContainer.setBackground(new java.awt.Color(255, 255, 255));

        Arrival.setBackground(new java.awt.Color(102, 102, 102));
        Arrival.setForeground(new java.awt.Color(255, 255, 255));
        Arrival.setText("Arrival");
        Arrival.setBorder(null);
        Arrival.setMaximumSize(new java.awt.Dimension(120, 35));
        Arrival.setMinimumSize(new java.awt.Dimension(120, 35));
        Arrival.setPreferredSize(new java.awt.Dimension(120, 35));
        Arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrivalActionPerformed(evt);
            }
        });

        Departures.setBackground(new java.awt.Color(102, 102, 102));
        Departures.setForeground(new java.awt.Color(255, 255, 255));
        Departures.setText("Departure");
        Departures.setBorder(null);
        Departures.setMaximumSize(new java.awt.Dimension(120, 35));
        Departures.setMinimumSize(new java.awt.Dimension(120, 35));
        Departures.setPreferredSize(new java.awt.Dimension(120, 35));
        Departures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeparturesActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton2.setText("BACK");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BottomContainerLayout = new javax.swing.GroupLayout(BottomContainer);
        BottomContainer.setLayout(BottomContainerLayout);
        BottomContainerLayout.setHorizontalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomContainerLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Departures, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );

        BottomContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Arrival, Departures});

        BottomContainerLayout.setVerticalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Departures, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        FlightTable.setBackground(new java.awt.Color(255, 255, 255));
        FlightTable.setForeground(new java.awt.Color(102, 102, 102));
        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ariline", "Aircraft", "Origin", "Destination", "Frequency", "Time", "Flight Number", "Duration", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(FlightTable);
        if (FlightTable.getColumnModel().getColumnCount() > 0) {
            FlightTable.getColumnModel().getColumn(0).setResizable(false);
            FlightTable.getColumnModel().getColumn(1).setResizable(false);
            FlightTable.getColumnModel().getColumn(2).setResizable(false);
            FlightTable.getColumnModel().getColumn(3).setResizable(false);
            FlightTable.getColumnModel().getColumn(4).setResizable(false);
            FlightTable.getColumnModel().getColumn(5).setResizable(false);
            FlightTable.getColumnModel().getColumn(6).setResizable(false);
            FlightTable.getColumnModel().getColumn(7).setResizable(false);
            FlightTable.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BottomContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(TopContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    
    //------------------DEPARTURE TABLE------------------------------
    public void loadFlightsToTableDeparture() {
        
        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        //INTIALIZE TABLE
        model.setRowCount(0);

        File file = new File(AdminOperations.Database_TimeTable_Departure_Path);
        
        //reads from file and then displays to Deparutre table
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;    

             

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    distanceCalculator distCalc = new distanceCalculator(rowData[2], rowData[3], rowData[1]);
                    
                    String airline = rowData[0];
                    String aircraft = rowData[1];
                    String origin = rowData[2];
                    String destination = rowData[3];
                    String freq = rowData[4];
                    String time = rowData[5];
                    String flightNo = rowData[6];

                    String distanceStr = "N/A";
                    String durationStr = "N/A";

                    try {
                 
                        distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

                       
                        double distVal = calc.calculateDistanceKm();
                        distanceStr = String.format("%.0f km", distVal);

                       
                        int totalMinutes = calc.calculateFlightDurationMinutes();
                        int hrs = totalMinutes / 60;
                        int mins = totalMinutes % 60;
                        durationStr = hrs + "h " + mins + "m";

                    } catch (Exception e) {
                        System.out.println("Calc Error: ");
                    }
                   
                    
                    String[] adjustedRow = {
                        airline, aircraft, origin, destination, freq, time, flightNo, 
                        durationStr, distanceStr 
                    };
                    model.addRow(adjustedRow);
                    
                }
            }
            br.close();

        } catch (IOException e) {
            System.out.println("Error loading departures");
        }
    }
    //-----------------------------------------------------------------------

    //------------------ARRIVAL TABLE------------------------------
    public void loadFlightsToTableArrival() {
  
        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        //INTIALIZE TABLE
        model.setRowCount(0);

        File file = new File(AdminOperations.Database_TimeTable_Arrivals_Path);

        //reads from file and then displays to Arrival table
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");
                    
                    distanceCalculator distCalc = new distanceCalculator(rowData[2], rowData[3], rowData[1]);
                    String airline = rowData[0];
                    String aircraft = rowData[1];
                    String origin = rowData[2];
                    String destination = rowData[3];
                    String freq = rowData[4];
                    String time = rowData[5];
                    String flightNo = (rowData.length == 7) ? rowData[6] : "";

                    String distanceStr = "N/A";
                    String durationStr = "N/A";


                    try {
                        distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);
                        double distVal = calc.calculateDistanceKm();
                        distanceStr = String.format("%.0f km", distVal);

                        int totalMinutes = calc.calculateFlightDurationMinutes();
                        durationStr = (totalMinutes / 60) + "h " + (totalMinutes % 60) + "m";
                    } catch (Exception e) {}

                    String[] adjustedRow = { 
                        airline, aircraft, origin, destination, freq, time, flightNo, 
                        durationStr, distanceStr 
                    };
                    model.addRow(adjustedRow);
                }
            }
            br.close();

        } catch (IOException e) {
            System.out.println("Error loading departures");
        }
    }
    //-----------------------------------------------------------------------
    
    //------------------DEFAULT TABLE VIEW------------------------------
    private String getActiveTimetablePath() {
        if (Arrival.getBackground().equals(Color.WHITE)) {
            return AdminOperations.Database_TimeTable_Arrivals_Path;
        } else {       
            return AdminOperations.Database_TimeTable_Departure_Path;
        }
    }
     //-----------------------------------------------------------------------
    
    public void searchFlights() {
        
        String filePath = getActiveTimetablePath();
        File file = new File(filePath);

        
        String searchTerm = SearchField.getText().trim().toLowerCase();

        
        String placeholderText = "search for a flight".toLowerCase();

      
        if (searchTerm.equals(placeholderText) || searchTerm.isEmpty()) {
            // Reload all flights based on what is active 
            if (Arrival.getBackground().equals(Color.WHITE)) {
                loadFlightsToTableArrival();
            } else {
                loadFlightsToTableDeparture();
            }
            return;
        }

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0); 

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    
                    boolean match = false;
                    for (String data : rowData) {
                        if (data.trim().toLowerCase().contains(searchTerm)) {
                            match = true;
                            break;
                        }
                    }

                    
                    if (match) {
                        String distanceStr = "N/A";
                        String durationStr = "N/A";

                        
                        try {
                            distanceCalculator calc = new distanceCalculator(rowData[2], rowData[3], rowData[1]);
                            double distVal = calc.calculateDistanceKm();
                            distanceStr = String.format("%.0f km", distVal);
                            int totalMinutes = calc.calculateFlightDurationMinutes();
                            durationStr = (totalMinutes / 60) + "h " + (totalMinutes % 60) + "m";
                        } catch (Exception e) {
                            System.out.println("Error in Calculating Time");
                        }
                        
                        String[] adjustedRow = {
                            rowData[0], rowData[1], rowData[2], rowData[3], rowData[4], rowData[5], rowData[6],
                            durationStr, distanceStr
                        };
                        model.addRow(adjustedRow);
                        
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading flight file for search");
        }
    }
    
    private void resetSearchField() {
        SearchField.setText("Search for a flight");
        SearchField.setForeground(Color.LIGHT_GRAY);
    }
    
    private void ArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrivalActionPerformed
        Arrival.setBackground(Color.WHITE);
        Arrival.setForeground(Color.BLACK);
        Departures.setBackground(Color.GRAY);
        Departures.setForeground(Color.WHITE);
        
        FlightTable.getColumnModel().getColumn(5).setHeaderValue("ETA");
        FlightTable.getTableHeader().repaint();
        
        loadFlightsToTableArrival();
        
        resetSearchField();
    }//GEN-LAST:event_ArrivalActionPerformed

    private void DeparturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeparturesActionPerformed
        Departures.setBackground(Color.WHITE);
        Departures.setForeground(Color.BLACK);
        Arrival.setBackground(Color.GRAY);
        Arrival.setForeground(Color.WHITE);
        
        FlightTable.getColumnModel().getColumn(5).setHeaderValue("ETD");
        FlightTable.getTableHeader().repaint();
        
        loadFlightsToTableDeparture();
        
        resetSearchField();
    }//GEN-LAST:event_DeparturesActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        searchFlights();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        SearchField.setText("");
        SearchField.setForeground(Color.BLACK);
    }//GEN-LAST:event_SearchFieldFocusGained

    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        if (SearchField.getText().trim().isEmpty()) {
            SearchField.setText("Search for a flight");
            SearchField.setForeground(Color.LIGHT_GRAY);
        }   
    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
      searchFlights();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        LoginForm displayLoginForm = new LoginForm();
        displayLoginForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFlightDisplayGuest().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Arrival;
    private javax.swing.JPanel BottomContainer;
    private javax.swing.JPanel Container;
    private javax.swing.JToggleButton Departures;
    private javax.swing.JTable FlightTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchContainer;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
