/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa;

import com.mycompany.lipadbantayoopdsa.popupInterface.addFlightScreen;
import com.mycompany.lipadbantayoopdsa.popupInterface.editFlightScreen_1;
import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.flightBooking.FlightBooking;
import com.mycompany.lipadbantayoopdsa.userAuthentication.LoginForm;
import com.mycompany.lipadbantayoopdsa.userAuthentication.UserDashboard;
import java.awt.*;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author Joshua
 */
public class MainFlightDisplayGuest extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFlightDisplayGuest.class.getName());
    
    private int selectedRow = -1;
    private String username; 
    /**
     * Creates new form MainFlightDisplay
     */
    
    public MainFlightDisplayGuest() {
        initComponents();
        loadFlightsToTableDeparture();
        intializeComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        TopContainer = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SearchContainer = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        BottomContainer = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();
        Combo_Airline = new javax.swing.JComboBox<>();
        Combo_Status = new javax.swing.JComboBox<>();
        Combo_Origin = new javax.swing.JComboBox<>();
        Combo_Aircraft = new javax.swing.JComboBox<>();
        Combo_Destination = new javax.swing.JComboBox<>();
        resetFilters = new javax.swing.JButton();
        applyFilters = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(255, 255, 255));

        TopContainer.setBackground(new java.awt.Color(153, 153, 153));

        Title.setBackground(new java.awt.Color(153, 153, 153));
        Title.setFont(new java.awt.Font("Santana-Black", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("LIPAD BANTAY");

        SearchContainer.setBackground(new java.awt.Color(255, 255, 255));

        SearchField.setText("Search for a flight");
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
        });
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(153, 153, 153));
        SearchButton.setText("Search");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchContainerLayout = new javax.swing.GroupLayout(SearchContainer);
        SearchContainer.setLayout(SearchContainerLayout);
        SearchContainerLayout.setHorizontalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        SearchContainerLayout.setVerticalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TopContainerLayout = new javax.swing.GroupLayout(TopContainer);
        TopContainer.setLayout(TopContainerLayout);
        TopContainerLayout.setHorizontalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TopContainerLayout.setVerticalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BottomContainer.setBackground(new java.awt.Color(255, 255, 255));
        BottomContainer.setForeground(new java.awt.Color(51, 51, 51));

        jToggleButton2.setText("BACK");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BottomContainerLayout = new javax.swing.GroupLayout(BottomContainer);
        BottomContainer.setLayout(BottomContainerLayout);
        BottomContainerLayout.setHorizontalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomContainerLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BottomContainerLayout.setVerticalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomContainerLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        FlightTable.setBackground(new java.awt.Color(255, 255, 255));
        FlightTable.setForeground(new java.awt.Color(0, 102, 204));
        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Status", "Airline", "Aircraft", "Origin", "Destination", "Frequency", "ETD", "ETA", "Flight Number", "Duration", "Distance", "Pax", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(FlightTable);
        if (FlightTable.getColumnModel().getColumnCount() > 0) {
            FlightTable.getColumnModel().getColumn(0).setResizable(false);
            FlightTable.getColumnModel().getColumn(1).setResizable(false);
            FlightTable.getColumnModel().getColumn(2).setResizable(false);
            FlightTable.getColumnModel().getColumn(3).setResizable(false);
            FlightTable.getColumnModel().getColumn(4).setResizable(false);
            FlightTable.getColumnModel().getColumn(5).setResizable(false);
            FlightTable.getColumnModel().getColumn(6).setResizable(false);
            FlightTable.getColumnModel().getColumn(7).setResizable(false);
            FlightTable.getColumnModel().getColumn(8).setResizable(false);
            FlightTable.getColumnModel().getColumn(9).setResizable(false);
            FlightTable.getColumnModel().getColumn(10).setResizable(false);
            FlightTable.getColumnModel().getColumn(11).setResizable(false);
            FlightTable.getColumnModel().getColumn(12).setResizable(false);
        }

        Combo_Airline.setBackground(new java.awt.Color(153, 153, 153));
        Combo_Airline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Status.setBackground(new java.awt.Color(153, 153, 153));
        Combo_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combo_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_StatusActionPerformed(evt);
            }
        });

        Combo_Origin.setBackground(new java.awt.Color(153, 153, 153));
        Combo_Origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Aircraft.setBackground(new java.awt.Color(153, 153, 153));
        Combo_Aircraft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Destination.setBackground(new java.awt.Color(153, 153, 153));
        Combo_Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        resetFilters.setText("Reset Filters");
        resetFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFiltersActionPerformed(evt);
            }
        });

        applyFilters.setText("Apply");
        applyFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFiltersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BottomContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Airline, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Aircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Origin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        ContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Combo_Airline, Combo_Status});

        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(TopContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_Airline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Aircraft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetFilters)
                    .addComponent(applyFilters))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    
    //------------------DEPARTURE TABLE------------------------------
    public void loadFlightsToTableDeparture() {
        ArrivalTimetableGenerator calculateArrival = new ArrivalTimetableGenerator();
        calculateArrival.generate();
        
        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);
        
        File file = new File(AdminOperations.Database_TimeTable_Departure_Path);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    // Ensure the line has enough parts to avoid ArrayIndexOutOfBoundsException
                    if (rowData.length >= 10) {
                        String airline = rowData[0];
                        String aircraft = rowData[1];
                        String origin = rowData[2];
                        String destination = rowData[3];
                        String freq = rowData[4];
                        String ETD = rowData[5];
                        String ETA = "";
                        String flightNo = rowData[6];
                        String flightPax = rowData[7];
                        String flightCargo = rowData[8];
                        String flightStatus = rowData[9];

                        String distanceStr = "N/A";
                        String durationStr = "N/A";

                        // Calculations
                        try {
                            distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);
                  
                            double distVal = calc.calculateDistanceKm();
                            distanceStr = String.format("%.0f km", distVal);

                            int totalMinutes = calc.calculateFlightDurationMinutes();
                            int durHrs = totalMinutes / 60;
                            int durMins = totalMinutes % 60;
                            durationStr = durHrs + "h " + durMins + "m";

                            int etdHours = Integer.parseInt(ETD.substring(0, 2));
                            int etdMins = Integer.parseInt(ETD.substring(2, 4));

        
                            int arrivalTotalMins = (etdHours * 60) + etdMins + totalMinutes;

                        
                            int etaHours = (arrivalTotalMins / 60) % 24; // % 24 handles midnight rollover
                            int etaMins = arrivalTotalMins % 60;
                            
                            ETA = String.format("%02d%02d", etaHours, etaMins);

                        } catch (Exception e) {
                            System.out.println("Calc Error: " + e.getMessage());
                            ETA = "N/A";
                        }

                    
                        Object[] adjustedRow = {
                            flightStatus,
                            airline, 
                            aircraft, 
                            origin,
                            destination, 
                            freq, 
                            ETD, 
                            ETA,
                            flightNo,
                            durationStr, 
                            distanceStr,
                            flightPax,
                            flightCargo
                        };

                        model.addRow(adjustedRow);
                        
                        applyTableStyle(flightStatus);

                        
                    }
                }
            }
        } catch (IOException e) {
            // Log error using your existing logger
            logger.log(Level.SEVERE, "Error loading departures", e);
        }
        
        
        File fileArrival = new File(AdminOperations.Database_TimeTable_Arrivals_Path);

        try (BufferedReader br = new BufferedReader(new FileReader(fileArrival))) {
            String line;

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    // Ensure the line has enough parts to avoid ArrayIndexOutOfBoundsException
                    if (rowData.length >= 10) {
                        String airline = rowData[0];
                        String aircraft = rowData[1];
                        String origin = rowData[2];
                        String destination = rowData[3];
                        String freq = rowData[4];
                        String ETD = rowData[5];
                        String ETA = "";
                        String flightNo = rowData[6];
                        String flightPax = rowData[7];
                        String flightCargo = rowData[8];
                        String flightStatus = rowData[9];

                        String distanceStr = "N/A";
                        String durationStr = "N/A";

                        // Calculations
                        try {
                            distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

                            double distVal = calc.calculateDistanceKm();
                            distanceStr = String.format("%.0f km", distVal);

                            int totalMinutes = calc.calculateFlightDurationMinutes();
                            int durHrs = totalMinutes / 60;
                            int durMins = totalMinutes % 60;
                            durationStr = durHrs + "h " + durMins + "m";

                            int etdHours = Integer.parseInt(ETD.substring(0, 2));
                            int etdMins = Integer.parseInt(ETD.substring(2, 4));

                            int arrivalTotalMins = (etdHours * 60) + etdMins + totalMinutes;

                            int etaHours = (arrivalTotalMins / 60) % 24; // % 24 handles midnight rollover
                            int etaMins = arrivalTotalMins % 60;

                            ETA = String.format("%02d%02d", etaHours, etaMins);

                        } catch (Exception e) {
                            System.out.println("Calc Error: " + e.getMessage());
                            ETA = "N/A";
                        }

                        Object[] adjustedRow = {
                            flightStatus,
                            airline,
                            aircraft,
                            origin,
                            destination,
                            freq,
                            ETD,
                            ETA,
                            flightNo,
                            durationStr,
                            distanceStr,
                            flightPax,
                            flightCargo
                        };

                        model.addRow(adjustedRow);

                        applyTableStyle(flightStatus);

                    }
                }
            }
        } catch (IOException e) {
            // Log error using your existing logger
            logger.log(Level.SEVERE, "Error loading departures", e);
        }  
    }
    //-----------------------------------------------------------------------

    
    //----------------------------------------------------------------------
    private void applyTableStyle(String flightStatus){
        if(flightStatus.equalsIgnoreCase("Scheduled")){
            DefaultTableCellRenderer statusRowRenderer = new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {

                    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                    String status = table.getValueAt(row, 0).toString();

                    if (status.equals("Scheduled")) {
                        c.setBackground(new Color(200, 255, 200)); 
                        c.setForeground(Color.BLACK);             
                    } else if (status.equals("Delayed")) {
                        c.setBackground(new Color(255, 213, 128)); 
                        c.setForeground(Color.BLACK);  
                    } else if (status.equals("Canceled")) {
                        c.setBackground(new Color(255, 128, 128)); 
                        c.setForeground(Color.BLACK);  
                    } else {
                        if (!isSelected) {
                            c.setBackground(table.getBackground());
                            c.setForeground(table.getForeground());
                        }
                    }

                    return c;
                }
            };

            for (int i = 0; i < FlightTable.getColumnCount(); i++) {
                FlightTable.getColumnModel().getColumn(i).setCellRenderer(statusRowRenderer);
            }
        }
    }
    //----------------------------------------------------------------------
    
    
     public void intializeComboBoxes(){
        
        // Flight Status;
        Combo_Status.removeAllItems();
        Combo_Status.addItem("N/A");
        Combo_Status.addItem("Scheduled");
        Combo_Status.addItem("Delayed");
        Combo_Status.addItem("Canceled");
        
        
        
        //Airline
        Combo_Airline.removeAllItems();
        Combo_Airline.addItem("N/A");
        try {
            File airlineMaster = new File(AdminOperations.Database_Airlines_Path);
            Scanner airlineReader = new Scanner(airlineMaster);
            // adds options for the combobox, reads from the ac database
            while(airlineReader.hasNextLine()){
                String arilineStringLine = airlineReader.nextLine();
                String arilineStringLineArray[] = arilineStringLine.split("-");
                Combo_Airline.addItem(arilineStringLineArray[0]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }
        
        
        
        //Aircraft
        Combo_Aircraft.removeAllItems();
        Combo_Aircraft.addItem("N/A");
        try {
            File aircraftMaster = new File(AdminOperations.Database_Aircarfts_Path);
            Scanner aircraftReader = new Scanner(aircraftMaster);
            // adds options for the combobox, reads from the ac database
            while(aircraftReader.hasNextLine()){
                String aircraftStringLine = aircraftReader.nextLine();
                String aircraftStringLineArray[] = aircraftStringLine.split("-");
                Combo_Aircraft.addItem(aircraftStringLineArray[0]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }
        
        
        
        
        //Origin
        Combo_Origin.removeAllItems();
        Combo_Origin.addItem("N/A");
        try {
            File originMaster = new File(AdminOperations.Database_Aiports_Path);
            Scanner originReader = new Scanner(originMaster);
            // adds options for the combobox, reads from the ac database
            while(originReader.hasNextLine()){
                String originStringLine = originReader.nextLine();
                String originStringLineArray[] = originStringLine.split("-");
                Combo_Origin.addItem(originStringLineArray[1]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }
        
        
        
        
        //Destination 
        Combo_Destination.removeAllItems();
        Combo_Destination.addItem("N/A");
        try {
            File destinationMaster = new File(AdminOperations.Database_Aiports_Path);
            Scanner destiantionReader = new Scanner(destinationMaster);
            // adds options for the combobox, reads from the ac database
            while(destiantionReader.hasNextLine()){
                String destinationStringLine = destiantionReader.nextLine();
                String destinationStringLineArray[] = destinationStringLine.split("-");
                Combo_Destination.addItem(destinationStringLineArray[1]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }
        
        
        
    }
    
    
    //----------------------------------------------------------------------
    public void searchFlights() {
        String searchTerm = SearchField.getText().trim().toLowerCase();
        String placeholderText = "search for a flight".toLowerCase();

        // If search is empty, reload the default view
        if (searchTerm.equals(placeholderText) || searchTerm.isEmpty()) {
            loadFlightsToTableDeparture();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);


        // Array of files to search through
        String[] filesToSearch = {
            AdminOperations.Database_TimeTable_Departure_Path,
            AdminOperations.Database_TimeTable_Arrivals_Path // Ensure this path exists in AdminOperations
        };

        for (String filePath : filesToSearch) {
            File file = new File(filePath);
            if (!file.exists()) {
                continue;
            }

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (!line.trim().isEmpty()) {
                        String[] rowData = line.split("-");

                        // Check if any part of the line matches the search term
                        boolean match = false;
                        for (String data : rowData) {
                            if (data.trim().toLowerCase().contains(searchTerm)) {
                                match = true;
                                break;
                            }
                        }

                        if (match && rowData.length >= 10) {
                            processAndAddSearchRow(model, rowData);
                        }
                    }
                }
            } catch (IOException e) {
                System.out.println("Error reading file: " + filePath);
            }
        }
    }

    
    private void processAndAddSearchRow(DefaultTableModel model, String[] rowData) {
        try {
            String airline = rowData[0];
            String aircraft = rowData[1];
            String origin = rowData[2];
            String destination = rowData[3];
            String freq = rowData[4];
            String ETD = rowData[5];
            String flightNo = rowData[6];
            String flightPax = rowData[7];
            String flightCargo = rowData[8];
            String flightStatus = rowData[9];

            distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

            // Calculations
            double distVal = calc.calculateDistanceKm();
            String distanceStr = String.format("%.0f km", distVal);

            int totalMinutes = calc.calculateFlightDurationMinutes();
            String durationStr = (totalMinutes / 60) + "h " + (totalMinutes % 60) + "m";

            // ETA Math
            int etdHours = Integer.parseInt(ETD.substring(0, 2));
            int etdMins = Integer.parseInt(ETD.substring(2, 4));
            int arrivalTotalMins = (etdHours * 60) + etdMins + totalMinutes;
            String ETA = String.format("%02d%02d", (arrivalTotalMins / 60) % 24, arrivalTotalMins % 60);

            Object[] row = {
                flightStatus, airline, aircraft, origin, destination,
                freq, ETD, ETA, flightNo, durationStr, distanceStr, flightPax, flightCargo
            };

            model.addRow(row);
        } catch (Exception e) {
            // Skip malformed rows
        }
    }
    
    
    
    
    
    //----------------------------------------------------------------------
    public void applyFilters() {
        // Array of files to filter through
        String[] filesToFilter = {
            AdminOperations.Database_TimeTable_Departure_Path,
            AdminOperations.Database_TimeTable_Arrivals_Path
        };

        // Get current filter values from UI
        String searchTerm = SearchField.getText().trim().toLowerCase();
        String placeholder = "search for a flight".toLowerCase();

        String selStatus = Combo_Status.getSelectedItem().toString();
        String selAirline = Combo_Airline.getSelectedItem().toString();
        String selAircraft = Combo_Aircraft.getSelectedItem().toString();
        String selOrigin = Combo_Origin.getSelectedItem().toString();
        String selDest = Combo_Destination.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0); // Clear table before filtering

        // Loop through both Departure and Arrival files
        for (String filePath : filesToFilter) {
            File file = new File(filePath);
            if (!file.exists()) {
                continue;
            }

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) {
                        continue;
                    }

                    String[] rowData = line.split("-");
                    if (rowData.length < 10) {
                        continue;
                    }

                    // Extract fields for comparison
                    String airline = rowData[0];
                    String aircraft = rowData[1];
                    String origin = rowData[2];
                    String destination = rowData[3];
                    String flightStatus = rowData[9];

                    // Check matches for Search Field
                    boolean matchesSearch = searchTerm.equals(placeholder) || searchTerm.isEmpty()
                            || line.toLowerCase().contains(searchTerm);

                    // Check matches for Combo Boxes
                    boolean matchesStatus = selStatus.equals("N/A") || flightStatus.equalsIgnoreCase(selStatus);
                    boolean matchesAirline = selAirline.equals("N/A") || airline.equalsIgnoreCase(selAirline);
                    boolean matchesAircraft = selAircraft.equals("N/A") || aircraft.equalsIgnoreCase(selAircraft);

                    // Matches Origin/Dest (Checking first 4 chars for airport codes like RPLL)
                    boolean matchesOrigin = selOrigin.equals("N/A") || origin.toLowerCase().contains(selOrigin.toLowerCase());
                    boolean matchesDest = selDest.equals("N/A") || destination.toLowerCase().contains(selDest.toLowerCase());

                    // If ALL conditions pass, add the row
                    if (matchesSearch && matchesStatus && matchesAirline && matchesAircraft && matchesOrigin && matchesDest) {
                        processAndAddSearchRow(model, rowData);
                    }
                }
            } catch (IOException e) {
                logger.log(Level.SEVERE, "Error filtering file: " + filePath, e);
            }
        }
    }
    
    private void resetSearchField() {
        SearchField.setText("Search for a flight");
        SearchField.setForeground(Color.LIGHT_GRAY);
    }
    
    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        searchFlights();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        SearchField.setText("");
        SearchField.setForeground(Color.BLACK);
    }//GEN-LAST:event_SearchFieldFocusGained

    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        if (SearchField.getText().trim().isEmpty()) {
            SearchField.setText("Search for a flight");
            SearchField.setForeground(Color.LIGHT_GRAY);
        }   
    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
      searchFlights();
      
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        LoginForm display = new LoginForm();
        display.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void Combo_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_StatusActionPerformed
        
    }//GEN-LAST:event_Combo_StatusActionPerformed

    private void resetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFiltersActionPerformed
        Combo_Aircraft.setSelectedIndex(0);
        Combo_Airline.setSelectedIndex(0);
        Combo_Destination.setSelectedIndex(0);
        Combo_Origin.setSelectedIndex(0);
        Combo_Status.setSelectedIndex(0);
        applyFilters();
    }//GEN-LAST:event_resetFiltersActionPerformed

    private void applyFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFiltersActionPerformed
        applyFilters();
    }//GEN-LAST:event_applyFiltersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFlightDisplayGuest().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomContainer;
    private javax.swing.JComboBox<String> Combo_Aircraft;
    private javax.swing.JComboBox<String> Combo_Airline;
    private javax.swing.JComboBox<String> Combo_Destination;
    private javax.swing.JComboBox<String> Combo_Origin;
    private javax.swing.JComboBox<String> Combo_Status;
    private javax.swing.JPanel Container;
    private javax.swing.JTable FlightTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchContainer;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopContainer;
    private javax.swing.JButton applyFilters;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton resetFilters;
    // End of variables declaration//GEN-END:variables
}
