/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa;

import com.mycompany.lipadbantayoopdsa.popupInterface.addFlightScreen;
import com.mycompany.lipadbantayoopdsa.popupInterface.editFlightScreen_1;
import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.Database.Timetable.SortingFunction;
import com.mycompany.lipadbantayoopdsa.Database.Timetable.SortingFunctionA;
import com.mycompany.lipadbantayoopdsa.userAuthentication.AirlineManagerDashboard;
import com.mycompany.lipadbantayoopdsa.popupInterface.addFlightScreen_M;
import com.mycompany.lipadbantayoopdsa.popupInterface.archiveScreen;
import com.mycompany.lipadbantayoopdsa.popupInterface.archiveScreen_M;
import com.mycompany.lipadbantayoopdsa.userAuthentication.LoginForm;
import com.mycompany.lipadbantayoopdsa.popupInterface.editFlightScreen_M;
import java.awt.Color;
import java.awt.Component;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author Joshua
 */
public class MainFlightDisplayManagers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFlightDisplayManagers.class.getName());
    
    private int selectedRow = -1;

    private String currentAirlineName;
    private String currentAirlinePrefix;
    /**
     * Creates new form MainFlightDisplay
     */
    public MainFlightDisplayManagers() {
        this("TEST", "TS");
        initComponents();
        loadFlightsToTableDeparture();
        ArrivalTimetableGenerator.generate();
    }
    
   
    
     public MainFlightDisplayManagers(String Airlinename, String Prefix) {
        initComponents();
        // overload consteructor for the airline manager since it will get the flno prefix and the airline name 
        this.currentAirlineName = Airlinename;
        this.currentAirlinePrefix = Prefix;
        
        Title.setText("LIPAD BANTAY (" + Airlinename.toUpperCase() + ")");

        loadFlightsToTableDeparture();
        intializeComboBoxes();
        ArrivalTimetableGenerator.generate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        TopContainer = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SearchContainer = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        BottomContainer = new javax.swing.JPanel();
        addFlight = new javax.swing.JToggleButton();
        deleteFlight = new javax.swing.JToggleButton();
        editFlight = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        deleteFlight1 = new javax.swing.JToggleButton();
        Combo_Status = new javax.swing.JComboBox<>();
        Combo_Aircraft = new javax.swing.JComboBox<>();
        Combo_Origin = new javax.swing.JComboBox<>();
        Combo_Destination = new javax.swing.JComboBox<>();
        applyFilters = new javax.swing.JButton();
        resetFilters = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();
        airlineName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(255, 255, 255));

        TopContainer.setBackground(new java.awt.Color(51, 153, 255));

        Title.setFont(new java.awt.Font("Santana-Black", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("LIPAD BANTAY");

        SearchContainer.setBackground(new java.awt.Color(255, 255, 255));

        SearchField.setText("Search for a flight");
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
        });
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(0, 102, 255));
        SearchButton.setText("Search");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchContainerLayout = new javax.swing.GroupLayout(SearchContainer);
        SearchContainer.setLayout(SearchContainerLayout);
        SearchContainerLayout.setHorizontalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        SearchContainerLayout.setVerticalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TopContainerLayout = new javax.swing.GroupLayout(TopContainer);
        TopContainer.setLayout(TopContainerLayout);
        TopContainerLayout.setHorizontalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TopContainerLayout.setVerticalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BottomContainer.setBackground(new java.awt.Color(255, 255, 255));

        addFlight.setBackground(new java.awt.Color(204, 255, 204));
        addFlight.setText("ADD");
        addFlight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightActionPerformed(evt);
            }
        });

        deleteFlight.setBackground(new java.awt.Color(255, 102, 102));
        deleteFlight.setText("ARCHIVE");
        deleteFlight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFlightActionPerformed(evt);
            }
        });

        editFlight.setBackground(new java.awt.Color(255, 153, 102));
        editFlight.setText("EDIT");
        editFlight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFlightActionPerformed(evt);
            }
        });

        jToggleButton1.setText("BACK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        deleteFlight1.setBackground(new java.awt.Color(255, 255, 153));
        deleteFlight1.setText("VIEW ARCHIVE");
        deleteFlight1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        deleteFlight1.setBorderPainted(false);
        deleteFlight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFlight1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BottomContainerLayout = new javax.swing.GroupLayout(BottomContainer);
        BottomContainer.setLayout(BottomContainerLayout);
        BottomContainerLayout.setHorizontalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomContainerLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteFlight1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        BottomContainerLayout.setVerticalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomContainerLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFlight1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        Combo_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combo_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_StatusActionPerformed(evt);
            }
        });

        Combo_Aircraft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combo_Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        applyFilters.setText("Apply");
        applyFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFiltersActionPerformed(evt);
            }
        });

        resetFilters.setText("Reset Filters");
        resetFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFiltersActionPerformed(evt);
            }
        });

        FlightTable.setBackground(new java.awt.Color(255, 255, 255));
        FlightTable.setForeground(new java.awt.Color(0, 102, 204));
        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Status", "Airline", "Aircraft", "Origin", "Destination", "Frequency", "ETD", "ETA", "Flight Number", "Duration", "Distance", "Pax", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(FlightTable);

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BottomContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(airlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Combo_Aircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combo_Origin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combo_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(applyFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(TopContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airlineName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Combo_Origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Combo_Aircraft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Combo_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetFilters)
                        .addComponent(applyFilters)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    
    
    //------------------DEPARTURE TABLE------------------------------
    public void loadFlightsToTableDeparture() {

        SortingFunction.sortFile();
        SortingFunctionA.sortFile();
        FlightTable.revalidate();
        FlightTable.repaint();

        ArrivalTimetableGenerator calculateArrival = new ArrivalTimetableGenerator();
        calculateArrival.generate();
        
        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);

        File file = new File(AdminOperations.Database_TimeTable_Departure_Path);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    if (currentAirlineName != null && !rowData[0].trim().equalsIgnoreCase(currentAirlineName)) {
                        continue; 
                    }
                    
                    // Ensure the line has enough parts to avoid ArrayIndexOutOfBoundsException
                    if (rowData.length >= 10) {
                        String airline = rowData[0];
                        String aircraft = rowData[1];
                        String origin = rowData[2];
                        String destination = rowData[3];
                        String freq = rowData[4];
                        String ETD = rowData[5];
                        String ETA = "";
                        String flightNo = rowData[6];
                        String flightPax = rowData[7];
                        String flightCargo = rowData[8];
                        String flightStatus = rowData[9];

                        String distanceStr = "N/A";
                        String durationStr = "N/A";

                        // Calculations
                        try {
                            distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

                            double distVal = calc.calculateDistanceKm();
                            distanceStr = String.format("%.0f km", distVal);

                            int totalMinutes = calc.calculateFlightDurationMinutes();
                            int durHrs = totalMinutes / 60;
                            int durMins = totalMinutes % 60;
                            durationStr = durHrs + "h " + durMins + "m";

                            int etdHours = Integer.parseInt(ETD.substring(0, 2));
                            int etdMins = Integer.parseInt(ETD.substring(2, 4));

                            int arrivalTotalMins = (etdHours * 60) + etdMins + totalMinutes;

                            int etaHours = (arrivalTotalMins / 60) % 24; // % 24 handles midnight rollover
                            int etaMins = arrivalTotalMins % 60;

                            ETA = String.format("%02d%02d", etaHours, etaMins);

                        } catch (Exception e) {
                            System.out.println("Calc Error: " + e.getMessage());
                            ETA = "N/A";
                        }

                        Object[] adjustedRow = {
                            flightStatus,
                            airline,
                            aircraft,
                            origin,
                            destination,
                            freq,
                            ETD,
                            ETA,
                            flightNo,
                            durationStr,
                            distanceStr,
                            flightPax,
                            flightCargo
                        };

                        model.addRow(adjustedRow);

                        applyTableStyle(flightStatus);

                    }
                }
            }
        } catch (IOException e) {
            // Log error using your existing logger
            logger.log(Level.SEVERE, "Error loading departures", e);
        }
        
          File fileArrival = new File(AdminOperations.Database_TimeTable_Arrivals_Path);

        try (BufferedReader br = new BufferedReader(new FileReader(fileArrival))) {
            String line;

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    
                    if (currentAirlineName != null && !rowData[0].trim().equalsIgnoreCase(currentAirlineName)) {
                        continue; 
                    }
                    
                    // Ensure the line has enough parts to avoid ArrayIndexOutOfBoundsException
                    if (rowData.length >= 10) {
                        String airline = rowData[0];
                        String aircraft = rowData[1];
                        String origin = rowData[2];
                        String destination = rowData[3];
                        String freq = rowData[4];
                        String ETD = rowData[5];
                        String ETA = "";
                        String flightNo = rowData[6];
                        String flightPax = rowData[7];
                        String flightCargo = rowData[8];
                        String flightStatus = rowData[9];

                        String distanceStr = "N/A";
                        String durationStr = "N/A";

                        // Calculations
                        try {
                            distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

                            double distVal = calc.calculateDistanceKm();
                            distanceStr = String.format("%.0f km", distVal);

                            int totalMinutes = calc.calculateFlightDurationMinutes();
                            int durHrs = totalMinutes / 60;
                            int durMins = totalMinutes % 60;
                            durationStr = durHrs + "h " + durMins + "m";

                            int etdHours = Integer.parseInt(ETD.substring(0, 2));
                            int etdMins = Integer.parseInt(ETD.substring(2, 4));

                            int arrivalTotalMins = (etdHours * 60) + etdMins + totalMinutes;

                            int etaHours = (arrivalTotalMins / 60) % 24; // % 24 handles midnight rollover
                            int etaMins = arrivalTotalMins % 60;

                            ETA = String.format("%02d%02d", etaHours, etaMins);

                        } catch (Exception e) {
                            System.out.println("Calc Error: " + e.getMessage());
                            ETA = "N/A";
                        }

                        Object[] adjustedRow = {
                            flightStatus,
                            airline,
                            aircraft,
                            origin,
                            destination,
                            freq,
                                ETD,
                            ETA,
                            flightNo,
                            durationStr,
                            distanceStr,
                            flightPax,
                            flightCargo
                        };

                        model.addRow(adjustedRow);

                        applyTableStyle(flightStatus);

                    }
                }
            }
        } catch (IOException e) {
            // Log error using your existing logger
            logger.log(Level.SEVERE, "Error loading departures", e);
        }
        
        
    }
    //-----------------------------------------------------------------------
    
    //----------------------------------------------------------------------
    private void applyTableStyle(String flightStatus) {
        DefaultTableCellRenderer statusRowRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (isSelected) {
                    c.setBackground(table.getSelectionBackground());
                    c.setForeground(table.getSelectionForeground());
                    return c;
                }

                String status = table.getValueAt(row, 0).toString();

                if (status.equals("Scheduled")) {
                    c.setBackground(new Color(200, 255, 200));
                    c.setForeground(Color.BLACK);
                } else if (status.equals("Delayed")) {
                    c.setBackground(new Color(255, 213, 128));
                    c.setForeground(Color.BLACK);
                } else if (status.equals("Canceled")) {
                    c.setBackground(new Color(255, 128, 128));
                    c.setForeground(Color.BLACK);
                } else {
                    c.setBackground(table.getBackground());
                    c.setForeground(table.getForeground());
                }

                return c;
            }
        };

        for (int i = 0; i < FlightTable.getColumnCount(); i++) {
            FlightTable.getColumnModel().getColumn(i).setCellRenderer(statusRowRenderer);
        }
    }

    //----------------------------------------------------------------------
    
    
    public void intializeComboBoxes() {

        // Flight Status;
        Combo_Status.removeAllItems();
        Combo_Status.addItem("N/A");
        Combo_Status.addItem("Scheduled");
        Combo_Status.addItem("Delayed");
        Combo_Status.addItem("Canceled");

        //Airline
        airlineName.setText(currentAirlineName);

        //Aircraft
        Combo_Aircraft.removeAllItems();
        Combo_Aircraft.addItem("N/A");
        try {
            File aircraftMaster = new File(AdminOperations.Database_Aircarfts_Path);
            Scanner aircraftReader = new Scanner(aircraftMaster);
            // adds options for the combobox, reads from the ac database
            while (aircraftReader.hasNextLine()) {
                String aircraftStringLine = aircraftReader.nextLine();
                String aircraftStringLineArray[] = aircraftStringLine.split("-");
                Combo_Aircraft.addItem(aircraftStringLineArray[0]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }

        //Origin
        Combo_Origin.removeAllItems();
        Combo_Origin.addItem("N/A");
        try {
            File originMaster = new File(AdminOperations.Database_Aiports_Path);
            Scanner originReader = new Scanner(originMaster);
            // adds options for the combobox, reads from the ac database
            while (originReader.hasNextLine()) {
                String originStringLine = originReader.nextLine();
                String originStringLineArray[] = originStringLine.split("-");
                Combo_Origin.addItem(originStringLineArray[1]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }

        //Destination 
        Combo_Destination.removeAllItems();
        Combo_Destination.addItem("N/A");
        try {
            File destinationMaster = new File(AdminOperations.Database_Aiports_Path);
            Scanner destiantionReader = new Scanner(destinationMaster);
            // adds options for the combobox, reads from the ac database
            while (destiantionReader.hasNextLine()) {
                String destinationStringLine = destiantionReader.nextLine();
                String destinationStringLineArray[] = destinationStringLine.split("-");
                Combo_Destination.addItem(destinationStringLineArray[1]);
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found ");
        }

    }
    
    
    
    
    //-----------------------------------------------------------------------
    
    public void searchFlights() {
        String searchTerm = SearchField.getText().trim().toLowerCase();
        String placeholderText = "search for a flight".toLowerCase();

        if (searchTerm.equals(placeholderText) || searchTerm.isEmpty()) {
            loadFlightsToTableDeparture();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);
        model.addRow(new String[]{"", "", "", "", "", "", "", "", "", "", "", "", ""});

        String[] filesToSearch = {
            AdminOperations.Database_TimeTable_Departure_Path,
            AdminOperations.Database_TimeTable_Arrivals_Path
        };

        for (String filePath : filesToSearch) {
            File file = new File(filePath);
            if (!file.exists()) {
                continue;
            }

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) {
                        continue;
                    }
                    String[] rowData = line.split("-");

                    boolean match = false;
                    for (String data : rowData) {
                        if (data.trim().toLowerCase().contains(searchTerm)) {
                            match = true;
                            break;
                        }
                    }

                    if (match && rowData.length >= 10) {
                        processAndAddSearchRow(model, rowData);
                    }
                }
            } catch (IOException e) {
                System.out.println("Error reading file: " + filePath);
            }
        }
    }
    
  
    public void processAndAddSearchRow(DefaultTableModel model, String[] rowData) {
        try {
            String airline = rowData[0];
            String aircraft = rowData[1];
            String origin = rowData[2];
            String destination = rowData[3];
            String freq = rowData[4];
            String ETD = rowData[5];
            String flightNo = rowData[6];
            String flightPax = rowData[7];
            String flightCargo = rowData[8];
            String flightStatus = rowData[9];

            distanceCalculator calc = new distanceCalculator(origin, destination, aircraft);

            // Calculate Distance and Duration
            double distVal = calc.calculateDistanceKm();
            String distanceStr = String.format("%.0f km", distVal);

            int totalMinutes = calc.calculateFlightDurationMinutes();
            String durationStr = (totalMinutes / 60) + "h " + (totalMinutes % 60) + "m";

            // ETA Math (1230 -> 12:30 + Duration)
            int etdHours = Integer.parseInt(ETD.substring(0, 2));
            int etdMins = Integer.parseInt(ETD.substring(2, 4));
            int arrivalTotalMins = (etdHours * 60) + etdMins + totalMinutes;
            String ETA = String.format("%02d%02d", (arrivalTotalMins / 60) % 24, arrivalTotalMins % 60);

            model.addRow(new Object[]{
                flightStatus, airline, aircraft, origin, destination,
                freq, ETD, ETA, flightNo, durationStr, distanceStr, flightPax, flightCargo
            });

            applyTableStyle(flightStatus);
        } catch (Exception e) {
            // Skip malformed rows safely
        }
    }
    
     
    //----------------------------------------------------------------------
    public void applyFilters() {
        String[] filesToFilter = {
            AdminOperations.Database_TimeTable_Departure_Path,
            AdminOperations.Database_TimeTable_Arrivals_Path
        };

        String searchTerm = SearchField.getText().trim().toLowerCase();
        String placeholder = "search for a flight".toLowerCase();

        String selStatus = Combo_Status.getSelectedItem().toString();
        String selAirline = airlineName.getText().toString();
        String selAircraft = Combo_Aircraft.getSelectedItem().toString();
        String selOrigin = Combo_Origin.getSelectedItem().toString();
        String selDest = Combo_Destination.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
        model.setRowCount(0);

        // Admin requirement: Empty first row
        model.addRow(new String[]{"", "", "", "", "", "", "", "", "", "", "", "", ""});

        for (String filePath : filesToFilter) {
            File file = new File(filePath);
            if (!file.exists()) {
                continue;
            }

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) {
                        continue;
                    }

                    String[] rowData = line.split("-");
                    if (rowData.length < 10) {
                        continue;
                    }

                    // Match checks
                    boolean matchesSearch = searchTerm.equals(placeholder) || searchTerm.isEmpty() || line.toLowerCase().contains(searchTerm);
                    boolean matchesStatus = selStatus.equals("N/A") || rowData[9].equalsIgnoreCase(selStatus);
                    boolean matchesAirline = selAirline.equals("N/A") || rowData[0].equalsIgnoreCase(selAirline);
                    boolean matchesAircraft = selAircraft.equals("N/A") || rowData[1].equalsIgnoreCase(selAircraft);

                    // Flexible matching for Origin/Dest
                    boolean matchesOrigin = selOrigin.equals("N/A") || rowData[2].toLowerCase().contains(selOrigin.toLowerCase());
                    boolean matchesDest = selDest.equals("N/A") || rowData[3].toLowerCase().contains(selDest.toLowerCase());

                    if (matchesSearch && matchesStatus && matchesAirline && matchesAircraft && matchesOrigin && matchesDest) {
                        processAndAddSearchRow(model, rowData);
                    }
                }
            } catch (IOException e) {
                logger.log(Level.SEVERE, "Filter error on " + filePath, e);
            }
        }
    }
    
    
    
    private void resetSearchField() {
        SearchField.setText("Search for a flight");
        SearchField.setForeground(Color.LIGHT_GRAY);
    }
    
    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        searchFlights();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        SearchField.setText("");
        SearchField.setForeground(Color.BLACK);
    }//GEN-LAST:event_SearchFieldFocusGained

    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        if (SearchField.getText().trim().isEmpty()) {
            SearchField.setText("Search for a flight");
            SearchField.setForeground(Color.LIGHT_GRAY);
        }   
    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
      searchFlights();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void addFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightActionPerformed
        addFlightScreen_M addPopUp = new addFlightScreen_M(currentAirlineName, currentAirlinePrefix);
    
        addPopUp.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                    loadFlightsToTableDeparture();
            }
        });

        addPopUp.setVisible(true);
        
    }//GEN-LAST:event_addFlightActionPerformed

    private void editFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFlightActionPerformed
        
        // 1. Get Selected Row
        selectedRow = FlightTable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a flight to edit.");
            return;
        }

        // 2. Extract ALL required data from the table model
        // Indices match your table columns: 
        // [0]Status, [1]Airline, [2]Aircraft, [3]Origin, [4]Dest, [5]Freq, [6]ETD, [8]FltNo, [11]Pax, [12]Cargo
        String status = FlightTable.getValueAt(selectedRow, 0).toString();
        String airline = FlightTable.getValueAt(selectedRow, 1).toString();
        String aircraft = FlightTable.getValueAt(selectedRow, 2).toString();
        String origin = FlightTable.getValueAt(selectedRow, 3).toString();
        String destination = FlightTable.getValueAt(selectedRow, 4).toString();
        String frequency = FlightTable.getValueAt(selectedRow, 5).toString();
        String time = FlightTable.getValueAt(selectedRow, 6).toString();
        String flightNumber = FlightTable.getValueAt(selectedRow, 8).toString();

        // NEW: Get Pax and Cargo
        String pax = FlightTable.getValueAt(selectedRow, 11).toString();
        String cargo = FlightTable.getValueAt(selectedRow, 12).toString();

        // 3. Open the Popup with ALL 10 arguments
        // This matches the new constructor we made earlier
        editFlightScreen_1 editPopUp = new editFlightScreen_1(
                airline,
                aircraft,
                origin,
                destination,
                frequency,
                time,
                flightNumber,
                pax, // Added
                cargo, // Added
                status // Added
        );

        // 4. Add listener to refresh table when closed
        editPopUp.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadFlightsToTableDeparture();
            }
        });

        editPopUp.setVisible(true);
    }//GEN-LAST:event_editFlightActionPerformed

    private void deleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFlightActionPerformed

        int selectedRow = FlightTable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a flight to archive.");
            return;
        }

        // Confirmation Dialog
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to ARCHIVE this flight? It will be moved to the Archive list.",
                "Confirm Archive",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String flightNumber = FlightTable.getValueAt(selectedRow, 8).toString();

            try {
                // 1. COPY to Archive File
                archiveFlightLine(flightNumber);

                // 2. DELETE from Active Files (Departure & Arrival)
                deleteLineFromFile(AdminOperations.Database_TimeTable_Departure_Path, flightNumber);
                deleteLineFromFile(AdminOperations.Database_TimeTable_Arrivals_Path, flightNumber);

                // 3. Refresh Table
                loadFlightsToTableDeparture();

                javax.swing.JOptionPane.showMessageDialog(this, "Flight archived successfully.");

            } catch (IOException e) {
                logger.log(Level.SEVERE, "Archive Error", e);
                javax.swing.JOptionPane.showMessageDialog(this, "Error archiving flight.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void archiveFlightLine(String flightNum) throws IOException {
        File source = new File(AdminOperations.Database_TimeTable_Departure_Path);
        File dest = new File(AdminOperations.Database_TimeTable_Archive_Path); // Ensure this path exists in AdminOperations

        // Create archive file if it doesn't exist
        if (!dest.exists()) {
            dest.createNewFile();
        }

        try (Scanner scanner = new Scanner(source); BufferedWriter writer = new BufferedWriter(new FileWriter(dest, true))) { // 'true' = append mode

            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] parts = line.split("-");
                // Check if this is the correct flight (Index 6 is Flight Number)
                if (parts.length > 6 && parts[6].equalsIgnoreCase(flightNum)) {
                    writer.write(line);
                    writer.newLine();
                    break; // Found and archived, exit loop
                }
            }
        }
    }

    
    private void deleteLineFromFile(String filePath, String flightNumberToRemove) throws IOException {
        File inputFile = new File(filePath);
        File tempFile = new File(inputFile.getParent(), "temp_deletion_" + inputFile.getName());

      
        if (!inputFile.exists()) {
            System.out.println("File not found: " + filePath);
            return;
        }

        try (Scanner reader = new Scanner(inputFile);
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            while (reader.hasNextLine()) {
                String line = reader.nextLine();

               
                if (!line.contains(flightNumberToRemove)) {
                    writer.write(line);
                    writer.newLine();
                }
            }
        }

        
        if (!inputFile.delete()) {
            if (!inputFile.delete()) {
                System.out.println("Could not delete original file: " + filePath);
                return;
            }
        }

        if (!tempFile.renameTo(inputFile)) {
            System.out.println("Could not rename temp file to: " + filePath);
        }
    }
    

    private void updateTimetableFile(String airline, String aircraft, String origin, String destination, String frequency, String time, String flightNumber) {
        File file = new File(AdminOperations.Database_TimeTable_Departure_Path);

        try {
            
            BufferedReader reader = new BufferedReader(new FileReader(file));
            StringBuilder fileContent = new StringBuilder();
            String line;

           
            while ((line = reader.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    
                    String[] rowData = line.split("-");

                    
                    if (rowData.length == 7) {
                       if (rowData[0].equals(airline) && rowData[1].equals(aircraft) && rowData[2].equals(origin)
                            && rowData[3].equals(destination) && rowData[4].equals(frequency) && rowData[5].equals(time)
                            && rowData[6].equals(flightNumber)) {
                            continue;
                        }
                    }

                    fileContent.append(line).append(System.lineSeparator());
                }
            }

            reader.close();

          
            BufferedWriter writer = new BufferedWriter(new FileWriter(file));
            writer.write(fileContent.toString());
            writer.close();

        } catch (IOException e) {
            logger.log(Level.SEVERE, "Error updating flight file after deletion.", e);
        }
    }//GEN-LAST:event_deleteFlightActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        AirlineManagerDashboard display = new AirlineManagerDashboard(currentAirlineName, currentAirlinePrefix);
        display.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void applyFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFiltersActionPerformed
        applyFilters();
    }//GEN-LAST:event_applyFiltersActionPerformed

    private void resetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFiltersActionPerformed
        Combo_Aircraft.setSelectedIndex(0);
        Combo_Destination.setSelectedIndex(0);
        Combo_Origin.setSelectedIndex(0);
        Combo_Status.setSelectedIndex(0);
        applyFilters();
    }//GEN-LAST:event_resetFiltersActionPerformed

    private void deleteFlight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFlight1ActionPerformed
        // TODO add your handling code here:
        archiveScreen_M display = new archiveScreen_M(currentAirlineName, currentAirlinePrefix);
        display.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteFlight1ActionPerformed

    private void Combo_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_StatusActionPerformed

    }//GEN-LAST:event_Combo_StatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFlightDisplayManagers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomContainer;
    private javax.swing.JComboBox<String> Combo_Aircraft;
    private javax.swing.JComboBox<String> Combo_Destination;
    private javax.swing.JComboBox<String> Combo_Origin;
    private javax.swing.JComboBox<String> Combo_Status;
    private javax.swing.JPanel Container;
    private javax.swing.JTable FlightTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchContainer;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopContainer;
    private javax.swing.JToggleButton addFlight;
    private javax.swing.JLabel airlineName;
    private javax.swing.JButton applyFilters;
    private javax.swing.JToggleButton deleteFlight;
    private javax.swing.JToggleButton deleteFlight1;
    private javax.swing.JToggleButton editFlight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton resetFilters;
    // End of variables declaration//GEN-END:variables
}
