/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa.flightBooking;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import com.mycompany.lipadbantayoopdsa.userAuthentication.UserDashboard;

/**
 *
 * @author alken
 */
public class FlightBooking extends javax.swing.JFrame {

    /**
     * Creates new form FlightBooking
     */
    
    private static final Logger logger = Logger.getLogger(FlightBooking.class.getName());
    
    public FlightBooking() {
        initComponents();
        
        loadFlightsToTableDeparture();
        ((DefaultTableModel) jTable2.getModel()).setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panel1.setBackground(new java.awt.Color(51, 153, 255));

        label1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Book Your Journey");

        SearchField.setText("Search for a flight");
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
        });
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(0, 102, 255));
        SearchButton.setText("Search");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        button1.setLabel("Book Flight");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Cancel Flight");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("Back");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Available Flights");

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Your Flights");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Airline", "Day", "Time", "Origin", "Destination"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "Day", "Time", "Origin", "Destination", "Flight Number"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1172, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadFlightsToTableDeparture() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String filePath = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Timetable/Departure_Timetable_Master - Copy.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            List<String[]> rows = new ArrayList<>();

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");
                    // Add only the first 5 columns for Departure table
                    if (rowData.length >= 5) {
                        String[] row = { rowData[0], rowData[4], rowData[5], rowData[2], rowData[3] };
                        rows.add(row);
                    }
                }
            }
            br.close();

            // Sort rows by Day and Time
            Collections.sort(rows, (row1, row2) -> {
                int dayComparison = row1[1].compareTo(row2[1]);
                if (dayComparison == 0) {
                    return row1[2].compareTo(row2[2]);
                }
                return dayComparison;
            });

            // Add sorted data to the table
            for (String[] row : rows) {
                model.addRow(row);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void loadFlightsToTableArrival() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String filePath = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Timetable/Arrival_Timetable_Master.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            List<String[]> rows = new ArrayList<>();

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");
                    // Add all 6 columns for Arrival table
                    if (rowData.length >= 6) {
                        String[] row = { rowData[0], rowData[4], rowData[5], rowData[2], rowData[3] };
                        rows.add(row);
                    }
                }
            }
            br.close();

            // Sort rows by Day and Time (you can adjust sorting criteria as needed)
            Collections.sort(rows, (row1, row2) -> {
                int dayComparison = row1[1].compareTo(row2[1]);
                if (dayComparison == 0) {
                    return row1[2].compareTo(row2[2]);
                }
                return dayComparison;
            });

            // Add sorted data to the table
            for (String[] row : rows) {
                model.addRow(row);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void saveBookingToTxt(String record) {
        String filePath = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Bookings.txt"; // Update the path if necessary
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath, true))) {
            writer.write(record);
            writer.newLine(); // Add a new line after each record
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving booking to file.");
            e.printStackTrace();
        }
    }
    
    private void removeBookingFromTxt(String record) {
        String filePath = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Bookings.txt"; // Update the path if necessary
        File file = new File(filePath);
        File tempFile = new File(file.getAbsolutePath() + ".temp");

        try (BufferedReader reader = new BufferedReader(new FileReader(file));
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = reader.readLine()) != null) {
                if (!line.trim().equals(record)) { // Skip the record to remove
                    writer.write(line);
                    writer.newLine();
                }
            }

            // Delete original file and rename the temp file
            if (file.delete()) {
                tempFile.renameTo(file);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error removing booking from file.");
            e.printStackTrace();
        }
    }
    
    private void searchFlights() {
        String searchQuery = SearchField.getText().toLowerCase(); // Get the search query and convert it to lowercase for case-insensitive search

        // First, clear the tables
        DefaultTableModel availableModel = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel bookedModel = (DefaultTableModel) jTable2.getModel();
        availableModel.setRowCount(0);
        bookedModel.setRowCount(0);

        // Re-load and filter the available flights for departure
        loadAndFilterFlightsToTableDeparture(searchQuery);

        // Re-load and filter the booked flights for arrival
        loadAndFilterFlightsToTableArrival(searchQuery);
    }

    private void loadAndFilterFlightsToTableDeparture(String searchQuery) {
        // 1. Target jTable2 specifically
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 

        // 2. This clears those blank rows you saw in the screenshot
        model.setRowCount(0); 

        String filePath = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Timetable/Arrival_Timetable_Master.txt";
        File file = new File(filePath);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            List<String[]> rows = new ArrayList<>();

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");

                    // 3. Ensure we have enough data (6 columns)
                    if (rowData.length >= 6) {
                        // This MUST have 6 items to fill all 6 columns in your UI
                        String[] row = { 
                            rowData[0], // Airline (Col 1)
                            rowData[4], // Day (Col 2)
                            rowData[5], // Time (Col 3)
                            rowData[2], // Origin (Col 4)
                            rowData[3], // Destination (Col 5)
                            rowData[1]  // Flight Number (Col 6)
                        };

                        if (matchesSearchQuery(row, searchQuery)) {
                            rows.add(row);
                        }
                    }
                }
            }

            // Add to table
            for (String[] row : rows) {
                model.addRow(row);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void loadAndFilterFlightsToTableArrival(String searchQuery) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String filePath = "src/main/java/com/mycompany/lipadbantayoopdsa/Database/Timetable/Arrival_Timetable_Master.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            List<String[]> rows = new ArrayList<>();

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] rowData = line.split("-");
                    // Add all 6 columns for Arrival table
                    if (rowData.length >= 6) {
                        String[] row = { rowData[0], rowData[4], rowData[5], rowData[2], rowData[3], rowData[6] };
                        // Filter the row based on the search query
                        if (matchesSearchQuery(row, searchQuery)) {
                            rows.add(row);
                        }
                    }
                }
            }
            br.close();

            // Sort rows by Day and Time (you can adjust sorting criteria as needed)
            Collections.sort(rows, (row1, row2) -> {
                int dayComparison = row1[1].compareTo(row2[1]);
                if (dayComparison == 0) {
                    return row1[2].compareTo(row2[2]);
                }
                return dayComparison;
            });

            // Add sorted and filtered data to the table
            for (String[] row : rows) {
                model.addRow(row);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // Utility method to check if the search query matches any part of the row
    private boolean matchesSearchQuery(String[] row, String searchQuery) {
        for (String field : row) {
            if (field.toLowerCase().contains(searchQuery)) {
                return true; // If any field contains the search query
            }
        }
        return false; // No match found in this row
    }
    
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        DefaultTableModel sourceModel = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel destModel = (DefaultTableModel) jTable2.getModel();
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a flight first.");
            return;
        }

        // Convert objects to Strings immediately
        String airline = sourceModel.getValueAt(selectedRow, 0).toString();
        String day     = sourceModel.getValueAt(selectedRow, 1).toString();
        String time    = sourceModel.getValueAt(selectedRow, 2).toString();
        String origin  = sourceModel.getValueAt(selectedRow, 3).toString();
        String dest    = sourceModel.getValueAt(selectedRow, 4).toString();
        String flightNum = "N/A"; 

        // Add to Your Flights table
        destModel.addRow(new Object[]{airline, day, time, origin, dest, flightNum});

        // SAVE TO FILE (Crucial: This format must match the cancellation format)
        String record = airline + " - " + origin + " - " + dest + " - " + time;
        saveBookingToTxt(record);

        // Remove from available table
        sourceModel.removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Flight Booked Successfully!");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        DefaultTableModel yourFlightsModel = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel availableModel = (DefaultTableModel) jTable1.getModel();

        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a booked flight to cancel.");
            return;
        }

        // Get data as Strings
        String airline = yourFlightsModel.getValueAt(selectedRow, 0).toString();
        String day     = yourFlightsModel.getValueAt(selectedRow, 1).toString();
        String time    = yourFlightsModel.getValueAt(selectedRow, 2).toString();
        String origin  = yourFlightsModel.getValueAt(selectedRow, 3).toString();
        String dest    = yourFlightsModel.getValueAt(selectedRow, 4).toString();

        // Create the record string to search for in the TXT file
        // MUST MATCH: airline + " - " + origin + " - " + dest + " - " + time
        String record = airline + " - " + origin + " - " + dest + " - " + time;

        // Remove from Database
        removeBookingFromTxt(record);

        // Move back to Available Table (5 columns)
        availableModel.addRow(new Object[]{airline, day, time, origin, dest});

        // Remove from UI
        yourFlightsModel.removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Flight Cancelled.");
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (topFrame != null) {
            topFrame.dispose();
        }
        try {
            new UserDashboard("UserPlaceholder").setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not open UserDashboard. Check file name.");
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        // TODO add your handling code here:

        SearchField.setText("");
        SearchField.setForeground(Color.BLACK);
    }//GEN-LAST:event_SearchFieldFocusGained

    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        // TODO add your handling code here:

        if (SearchField.getText().trim().isEmpty()) {
            SearchField.setText("Search for a flight");
            SearchField.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
        searchFlights();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        searchFlights();
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> new FlightBooking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
