/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa.flightBooking;


import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.distanceCalculator;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import com.mycompany.lipadbantayoopdsa.userAuthentication.UserDashboard;
import java.io.FileNotFoundException;

/**
 *
 * @author alken
 */
public class FlightBooking extends javax.swing.JFrame {

    /**
     * Creates new form FlightBooking
     */
    
    private String username;
    private String filterOrigin;
    private String filterDest;
    private String filterDate;

    public FlightBooking(String username, String origin, String dest, String date) {
        this.username = username;
        this.filterOrigin = origin;
        this.filterDest = dest;
        this.filterDate = date;

        initComponents(); 
        loadFilteredFlights();
        loadUserBookings();
        
        this.addWindowFocusListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
                loadUserBookings();
            }
        });
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panel1.setBackground(new java.awt.Color(51, 153, 255));

        label1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Book Your Journey");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        button1.setLabel("Book Flight");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Cancel Flight");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("Back");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Available Flights");

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Your Flights");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "AcType", "Day", "Time", "Origin", "Destination", "Flight Number", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "AcType", "Day", "Time", "Origin", "Destination", "Flight Number", "Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private double getAirlineRate(String airlineName) {
        File file = new File(AdminOperations.Database_Airlines_Path);
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("-");
                // Format: AIRASIA-Z2-2.50
                if (parts.length >= 3 && parts[0].equalsIgnoreCase(airlineName)) {
                    return Double.parseDouble(parts[2]);
                }
            }
        } catch (Exception e) {
            System.out.println("Rate not found");
        }
        return 1.0; // Default rate
    }
    
    private double getBaseFare(String airline, String originStr, String destStr) {
        String fileName = "Routes_" + airline + ".txt";
        File file = new File("src/main/java/com/mycompany/lipadbantayoopdsa/Database/Routes/" + fileName);

        // Debugging: Print if file is found
        if (!file.exists()) {
            System.out.println("Price File Not Found: " + file.getAbsolutePath());
            return 1500.0;
        }

        try  (BufferedReader br = new BufferedReader(new FileReader(file))){
            
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("-");
                // Format: A320(0)-RPLL(Manila)(1)-RPSP(Panglao)(2)-1500(3)
                if (parts.length >= 4) {
                    String fileOrigin = parts[1];
                    String fileDest = parts[2];

                    boolean matchDirect = fileOrigin.contains(this.filterOrigin) && fileDest.contains(this.filterDest);

                    boolean matchReverse = fileOrigin.contains(this.filterDest) && fileDest.contains(this.filterOrigin);

                    if (matchDirect || matchReverse) {
                        return Double.parseDouble(parts[3].trim());
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("There was an error in finding the Base rate of the route");
        }

        return 1500.0; // Default Fallbakc of 1500 if teh base rate is not found on the file 
    }
    
    
    
    private String getDayCode(String dateStr) {
        try {
            java.util.Date date = new java.text.SimpleDateFormat("MM/dd/yyyy").parse(dateStr);
            String dayName = new java.text.SimpleDateFormat("EEEE").format(date);
            switch (dayName) {
                case "Monday":
                    return "M";
                case "Tuesday":
                    return "TU";
                case "Wednesday":
                    return "W";
                case "Thursday":
                    return "TH";
                case "Friday":
                    return "F";
                case "Saturday":
                    return "ST";
                case "Sunday":
                    return "SU";
                default:
                    return "";
            }
        } catch (Exception e) {
            return "";
        }
    }

    public void loadFilteredFlights() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String selectedDayCode = getDayCode(this.filterDate);
        String[] filesToSearch = {
            AdminOperations.Database_TimeTable_Departure_Path,
            AdminOperations.Database_TimeTable_Arrivals_Path
        };

        for (String path : filesToSearch) {
            File file = new File(path);
            if (!file.exists()) {
                continue;
            }

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    String[] rowData = line.trim().split("-");

                    // Format: Airline(0)-AcType(1)-Origin(2)-Dest(3)-Freq(4)-Time(5)-No(6)-Pax(7)-Cargo(8)-Status(9)
                    if (rowData.length >= 10) {
                        String airline = rowData[0];
                        String acType = rowData[1];
                        String dbOrigin = rowData[2]; 
                        String dbDest = rowData[3]; 
                        String dbFreq = rowData[4];
                        String time = rowData[5];
                        String flightNo = rowData[6];
                        String status = rowData[9];

                        
                        boolean matchesRoute = dbOrigin.toUpperCase().contains(filterOrigin.toUpperCase())
                                && dbDest.toUpperCase().contains(filterDest.toUpperCase());
                        boolean matchesDate = dbFreq.equalsIgnoreCase("E") || dbFreq.contains(selectedDayCode);

                        if (matchesRoute && matchesDate) {
                            
                            distanceCalculator calc = new distanceCalculator(filterOrigin, filterDest, acType);
                            double realDistance = calc.calculateDistanceKm();

                            
                            double base = getBaseFare(airline, dbOrigin, dbDest);
                            double rate = getAirlineRate(airline);

                            
                            double finalPrice = base + (rate * realDistance);
                            String priceStr = String.format("%.2f", finalPrice);

                            model.addRow(new Object[]{
                                airline, 
                                acType, 
                                dbFreq,
                                time, 
                                dbOrigin, 
                                dbDest, 
                                flightNo, 
                                priceStr, 
                                status

                            });
                        }
                    }
                }
            } catch (IOException e) {
                System.out.println("There was an error in filtering the flights");
            }
        }
    }
    
    
    
    public void loadFlightsToTableDeparture() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        File file = new File(AdminOperations.Database_TimeTable_Departure_Path);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            
            String line;
            List<String[]> rows = new ArrayList<>();

            while ((line = br.readLine()) != null) {
                String trimmedLine = line.trim();
                if (trimmedLine.isEmpty()) {
                    continue;
                }

                String[] rowData = trimmedLine.split("-");

            
                if (rowData.length >= 6) {
                    String flightNum = (rowData.length > 6) ? rowData[6] : "ID-ERR";

                    String[] row = {
                        rowData[0], 
                        rowData[4], 
                        rowData[5],
                        rowData[2], 
                        rowData[3], 
                        flightNum 
                    };
                    rows.add(row);
                }
            }

            
            Collections.sort(rows, (r1, r2) -> {
                int dayComp = r1[1].compareTo(r2[1]);
                return (dayComp != 0) ? dayComp : r1[2].compareTo(r2[2]);
            });

            for (String[] row : rows) {
                model.addRow(row);
            }

        } catch (IOException e) {
            System.out.println("File Not Found Departures");        
        }
    }

    public void loadFlightsToTableArrival() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        File file = new File(AdminOperations.Database_TimeTable_Arrivals_Path);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            
            String line;
            List<String[]> rows = new ArrayList<>();

            while ((line = br.readLine()) != null) {
                String trimmedLine = line.trim();
                if (trimmedLine.isEmpty()) continue;

                String[] rowData = trimmedLine.split("-");

                if (rowData.length >= 6) {
                    String flightNum = (rowData.length > 6) ? rowData[6] : "ID-ERR";

                    String[] row = { 
                        rowData[0], 
                        rowData[4], 
                        rowData[5], 
                        rowData[2], 
                        rowData[3], 
                        flightNum   
                    };
                    rows.add(row);
                }
            }

           
            Collections.sort(rows, (r1, r2) -> {
                int dayComp = r1[1].compareTo(r2[1]);
                return (dayComp != 0) ? dayComp : r1[2].compareTo(r2[2]);
            });

            for (String[] row : rows) model.addRow(row);

        } catch (IOException e) {
            System.out.println("File Not Found Arrivals");  
        }
    }
    
    private void loadUserBookings() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        
        model.setColumnIdentifiers(new String[]{
            "Airline", "AcType", "Day", "Time", "Origin", "Dest", "Flight No", "Date", "Seat"
        });

        String userHeader = "(" + this.username + ")";
        File file = new File(AdminOperations.Database_Bookings_Path);

        if (!file.exists()) {
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            boolean insideUser = false;
            while ((line = br.readLine()) != null) {
                String trimmed = line.trim();
                if (trimmed.startsWith("(") && !trimmed.equals(userHeader)) {
                    insideUser = false;
                }
                if (trimmed.equals(userHeader)) {
                    insideUser = true;
                    continue;
                }
                if (insideUser && trimmed.contains(" - ")) {
                    // Format: Airline(0)-AcType(1)-Origin(2)-Dest(3)-Time(4)-FNo(5)-Day(6)-Status(7)-Date(8)-Seat(9)
                    String[] parts = trimmed.split(" - ");

                    if (parts.length >= 10) {
                        model.addRow(new Object[]{
                            parts[0],
                            parts[1], 
                            parts[6], 
                            parts[4], 
                            parts[2], 
                            parts[3], 
                            parts[5], 
                            parts[8], 
                            parts[9] 
                        });
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("Error in loading User Booking");
        }
    }
    
    

    private void saveCancellationRequest(String requestData) {
        File file = new File(AdminOperations.Database_CancelRequests_Path);
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(file, true))) {
            
            bw.write(requestData);
            bw.newLine();
            bw.flush();
        } catch (IOException e){
            System.out.println("There was an error in loading the cancellation reqeusts");
        }
        
        System.out.println("SUCCESS: Request logged in " + AdminOperations.Database_CancelRequests_Path);
        
        
    }
    
    private boolean isCancellationPending(String flightNumber) {
        File file = new File(AdminOperations.Database_CancelRequests_Path);
        if (!file.exists()) 
            return false;

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = br.readLine()) != null) {
                String[] parts = line.split(" \\| ");

                if (parts.length >= 6) {
                    String savedUser = parts[0].trim();
                    String savedFlightNum = parts[2].trim();
                    String savedStatus = parts[5].trim();

                    if (savedUser.equals(this.username) && 
                        savedFlightNum.equals(flightNumber) && 
                        savedStatus.equalsIgnoreCase("PENDING")) {
                        return true; 
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("There was an error in the Cancelation request");
        }
        return false;
    }
    
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a flight.");
            return;
        }
        // Gets the value of the table
        String airline = jTable1.getValueAt(selectedRow, 0).toString();
        String acType = jTable1.getValueAt(selectedRow, 1).toString();
        String day = jTable1.getValueAt(selectedRow, 2).toString();
        String time = jTable1.getValueAt(selectedRow, 3).toString();
        String origin = jTable1.getValueAt(selectedRow, 4).toString();
        String dest = jTable1.getValueAt(selectedRow, 5).toString();
        String fNo = jTable1.getValueAt(selectedRow, 6).toString();
        String price = jTable1.getValueAt(selectedRow, 7).toString();
        String status = jTable1.getValueAt(selectedRow, 8).toString();

        BookingDetailsPopup popup = new BookingDetailsPopup(airline, acType, day, time, origin, dest, fNo, status, this.filterDate, price, this.username);

        popup.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadUserBookings();
                loadFilteredFlights();
            }
        });
        popup.setVisible(true);
    
    }//GEN-LAST:event_button1ActionPerformed

    
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a booking to cancel.");
            return;
        }

        
        String airline = jTable2.getValueAt(selectedRow, 0).toString();
        String flightNum = jTable2.getValueAt(selectedRow, 6).toString();
        String date = jTable2.getValueAt(selectedRow, 7).toString();
        String seat = jTable2.getValueAt(selectedRow, 8).toString();

        if (isCancellationPending(flightNum)) {
            JOptionPane.showMessageDialog(this,
                    "A cancellation request for Flight " + flightNum + " is already pending approval.\n"
                    + "Please wait for the Airline Manager to process your request.",
                    "Request Already Submitted",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Format: User | Airline | Flight | Date | Seat | REQUESTED | PENDING
        String cancelRequest = String.format("%s | %s | %s | %s | %s | REQUESTED | PENDING",
                this.username, airline, flightNum, date, seat);

        saveCancellationRequest(cancelRequest);
        JOptionPane.showMessageDialog(this, "Cancellation request sent for approval.");
    }//GEN-LAST:event_button2ActionPerformed

    
    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        new UserDashboard(this.username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
