/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa.flightBooking;

import com.mycompany.lipadbantayoopdsa.AdminOperations;
import com.mycompany.lipadbantayoopdsa.userAuthentication.UserDashboard;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Scanner;
import java.util.Date;


/**
 *
 * @author Joshua
 */
public class FlightPicker extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightPicker.class.getName());

    // there are 408 active airports in the philippines but just chanhe this value  if theres an addition of an airport 
    private int activeAirportCount = 60;
    private String[] airportNames = new String[activeAirportCount]; 
    private String[] airportCodes = new String[activeAirportCount];
    private int airportCount = 0; 
    
    private String currentUserName; 
    
    
    public FlightPicker() {
        this("Test");
    }
    
    public FlightPicker(String loggedInUsername) {
        initComponents();
        this.currentUserName = loggedInUsername;
        intializeComboBoxes();
        
        DateChooser.setMinSelectableDate(new Date());
        DateChooser.getDateEditor().setEnabled(false);
        
        errorDate.setText(" ");
        errorOrigin.setText(" ");
        errorDest.setText(" ");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        Title = new java.awt.Label();
        originDropDown = new javax.swing.JComboBox<>();
        originLabel = new javax.swing.JLabel();
        noticeLabel = new javax.swing.JLabel();
        destLabel = new javax.swing.JLabel();
        destinationDropDown = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        FindFlights = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        errorOrigin = new javax.swing.JLabel();
        errorDest = new javax.swing.JLabel();
        errorDate = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panel2.setBackground(new java.awt.Color(51, 153, 255));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Book Your Journey");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        originDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        originLabel.setBackground(new java.awt.Color(102, 102, 102));
        originLabel.setForeground(new java.awt.Color(51, 51, 51));
        originLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        originLabel.setText("ORIGIN");

        noticeLabel.setBackground(new java.awt.Color(102, 102, 102));
        noticeLabel.setForeground(new java.awt.Color(51, 51, 51));
        noticeLabel.setText("FLIGHT (One Way Ticket Only)");

        destLabel.setBackground(new java.awt.Color(102, 102, 102));
        destLabel.setForeground(new java.awt.Color(51, 51, 51));
        destLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destLabel.setText("DESTINATION");

        destinationDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        FindFlights.setBackground(new java.awt.Color(255, 255, 153));
        FindFlights.setForeground(new java.awt.Color(51, 51, 51));
        FindFlights.setText("Find Flights");
        FindFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindFlightsActionPerformed(evt);
            }
        });

        dateLabel.setBackground(new java.awt.Color(102, 102, 102));
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("DATE (M/D/Y)");

        errorOrigin.setText("placeholder");

        errorDest.setText("placeholder");

        errorDate.setText("placeholder");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(backButton)
                        .addGap(169, 169, 169)
                        .addComponent(FindFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noticeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(originDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(originLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errorOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(destinationDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(destLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errorDest, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errorDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(69, 69, 69))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DateChooser, destinationDropDown, originDropDown});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(noticeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(originLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(originDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorOrigin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorDate))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(destLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(destinationDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorDest)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(FindFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DateChooser, destinationDropDown, originDropDown});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void intializeComboBoxes() {
        originDropDown.removeAllItems();
        destinationDropDown.removeAllItems();
        originDropDown.addItem("N/A");
        destinationDropDown.addItem("N/A");
        airportCount = 0;

        try {
            File master = new File(AdminOperations.Database_Aiports_Path);
            Scanner reader = new Scanner(master);
            while (reader.hasNextLine()) {
                String line = reader.nextLine().trim();
                if (line.isEmpty()) {
                    continue;
                }

                // Format: Alcantara-RPVU-1390-12/18/39/N-122/04/46/E
                String[] parts = line.split("-");
                if (parts.length >= 2) {
                    String cityName = parts[0]; // Alcantara
                    String icaoCode = parts[1]; // RPVU

                   
                    if (airportCount < airportNames.length) {
                        airportNames[airportCount] = cityName;
                        airportCodes[airportCount] = icaoCode;
                        airportCount++;
                    }

                    // Display only the name
                    originDropDown.addItem(cityName);
                    destinationDropDown.addItem(cityName);
                }
            }
            reader.close();
        } catch (FileNotFoundException e) {
            System.out.println("Airport file not found");
        }
    }
    
    
    
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        UserDashboard display = new UserDashboard(currentUserName);
        display.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    
    
    
    
    private void FindFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindFlightsActionPerformed
        if (checkValidty()) {
            String originName = originDropDown.getSelectedItem().toString();
            String destName = destinationDropDown.getSelectedItem().toString();


            String originCode = "";
            for (int i = 0; i < airportCount; i++) {
                if (airportNames[i].equals(originName)) {
                    originCode = airportCodes[i];
                    break;
                }
            }

            String destCode = "";
            for (int i = 0; i < airportCount; i++) {
                if (airportNames[i].equals(destName)) {
                    destCode = airportCodes[i];
                    break;
                }
            }
            

            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            String finalDate = sdf.format(DateChooser.getDate());

            // Filters out the Flights in the Fligth Bookings
            FlightBooking bookingScreen = new FlightBooking(this.currentUserName, originCode, destCode, finalDate);
            bookingScreen.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_FindFlightsActionPerformed

 
    public boolean checkValidty() {

        boolean isValid = true;


        String origin = originDropDown.getSelectedItem().toString();
        String dest = destinationDropDown.getSelectedItem().toString();
        java.util.Date dateObj = DateChooser.getDate();


        if (origin.equals("N/A")) {
            errorOrigin.setText("Please select an origin");
            errorOrigin.setForeground(Color.RED);
            isValid = false;
        }

 
        if (dest.equals("N/A")) {
            errorDest.setText("Please select a destination");
            errorDest.setForeground(Color.RED);
            isValid = false;
        }

    
        if (!origin.equals("N/A") && !dest.equals("N/A") && origin.equals(dest)) {
            errorDest.setText("Dest cannot be same as Origin"); // Set error on Dest label
            errorDest.setForeground(Color.RED);
            isValid = false;
        }

  
        if (dateObj == null) {
            errorDate.setText("Please select a date");
            errorDate.setForeground(Color.RED);
            isValid = false;
        }

        return isValid;

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlightPicker().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton FindFlights;
    private java.awt.Label Title;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel destLabel;
    private javax.swing.JComboBox<String> destinationDropDown;
    private javax.swing.JLabel errorDate;
    private javax.swing.JLabel errorDest;
    private javax.swing.JLabel errorOrigin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel noticeLabel;
    private javax.swing.JComboBox<String> originDropDown;
    private javax.swing.JLabel originLabel;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
