/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipadbantayoopdsa.flightBooking;

import static com.mycompany.lipadbantayoopdsa.AdminOperations.Database_Bookings_Path;
import java.awt.Color;
import java.io.File;
import javax.swing.*;
import java.util.*;
import java.io.*;
/**
 *
 * @author Joshua
 */
public class paymentOptions extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(paymentOptions.class.getName());

    
    
    private String pendingRecord;
    private String username;
    private String price;
    private String selectedMethod = "";
    
    
    
    /**
     * Creates new form paymentOptions
     */
    public paymentOptions() {
        initComponents();
    }
    
    
    public paymentOptions(String fullRecord, String price, String username) {
        this.pendingRecord = fullRecord;
        this.username = username;
        
        if (price.contains(" - ")) {
            String[] parts = price.split(" - ");
            this.price = parts[parts.length - 1]; 
        } else {
            this.price = price;
        }

        initComponents();
        amount.setText("Total Amount: PHP " + this.price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        topContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        otc = new javax.swing.JButton();
        gcash = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        number = new javax.swing.JLabel();
        numberField = new javax.swing.JTextField();
        adress = new javax.swing.JLabel();
        adressField = new javax.swing.JTextField();
        bottomContainer = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        card = new javax.swing.JButton();
        cvc = new javax.swing.JLabel();
        cvcField = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));

        topContainer.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENT");

        javax.swing.GroupLayout topContainerLayout = new javax.swing.GroupLayout(topContainer);
        topContainer.setLayout(topContainerLayout);
        topContainerLayout.setHorizontalGroup(
            topContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topContainerLayout.setVerticalGroup(
            topContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topContainerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        otc.setBackground(new java.awt.Color(153, 153, 153));
        otc.setText("Over The Counter");
        otc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otcActionPerformed(evt);
            }
        });

        gcash.setBackground(new java.awt.Color(153, 153, 153));
        gcash.setText("Gcash");
        gcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcashActionPerformed(evt);
            }
        });

        name.setText("Name:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        number.setText("Number");

        adress.setText("Adress");

        bottomContainer.setBackground(new java.awt.Color(255, 255, 255));

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        confirm.setBackground(new java.awt.Color(153, 255, 153));
        confirm.setForeground(new java.awt.Color(51, 51, 51));
        confirm.setText("confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomContainerLayout = new javax.swing.GroupLayout(bottomContainer);
        bottomContainer.setLayout(bottomContainerLayout);
        bottomContainerLayout.setHorizontalGroup(
            bottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomContainerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomContainerLayout.setVerticalGroup(
            bottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomContainerLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(bottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(33, 33, 33))
        );

        card.setBackground(new java.awt.Color(153, 153, 153));
        card.setText("Card");
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });

        cvc.setText("Cvc");

        amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amount.setText("jLabel2");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottomContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cvc)
                                    .addComponent(adress)
                                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cvcField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(gcash, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(topContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card)
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gcash)
                        .addComponent(otc)))
                .addGap(47, 47, 47)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addGap(11, 11, 11)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number)
                    .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress)
                    .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        if (selectedMethod.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a payment method.");
            return;
        }

        String inputName = nameField.getText().trim();
        String inputNumber = numberField.getText().trim();
        String inputAdress = adressField.getText().trim();
        String inputCVC = cvcField.getText().trim();

        if (inputName.isEmpty() || inputNumber.isEmpty() || inputAdress.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        String paymentDetails = "";

        switch (selectedMethod) {
            case "CARD":
                if (inputCVC.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter CVC.");
                    return;
                }
                paymentDetails = "CARD - " + inputName + " - " + inputNumber + " - " + inputAdress + " - " + "PENDING";
                break;
            case "GCASH":
                paymentDetails = "GCASH - " + inputName + " - " + inputNumber + " - " + inputAdress + " - " + "PENDING";
                break;
            case "OTC":
                paymentDetails = "OTC - " + inputName + " - " + inputNumber + " - " + inputAdress + " - " + "PENDING";
                break;
        }
        String finalRecordToWrite = pendingRecord + " - " + paymentDetails;

        saveFinalBooking(finalRecordToWrite);

        JOptionPane.showMessageDialog(this, "Booking Successful!");
        
        this.dispose();
    }//GEN-LAST:event_confirmActionPerformed

    
    private void saveFinalBooking(String record) {
        File file = new File(Database_Bookings_Path);
        List<String> allLines = new ArrayList<>();
        String userHeader = "(" + this.username + ")";
        boolean sectionFound = false;

        try {
            if (file.exists()) {
                try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        allLines.add(line);
                    }
                }
            }
            for (int i = 0; i < allLines.size(); i++) {
                if (allLines.get(i).trim().equals(userHeader)) {
                    allLines.add(i + 1, record);
                    sectionFound = true;
                    break;
                }
            }
            if (!sectionFound) {
                allLines.add(userHeader);
                allLines.add(record);
            }
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
                for (String line : allLines) {
                    bw.write(line);
                    bw.newLine();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    
    private void gcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcashActionPerformed
        selectedMethod = "GCASH";
        gcash.setBackground(Color.GRAY);
        gcash.setForeground(Color.BLACK);
        
        card.setBackground(Color.WHITE);
        card.setForeground(Color.GRAY);
        otc.setBackground(Color.WHITE);
        otc.setForeground(Color.GRAY);
        
        name.setText("Name");
        adress.setText("Adress");
        number.setText("GCash No.");
        
        cvc.setVisible(false);
        cvcField.setVisible(false);
    }//GEN-LAST:event_gcashActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        selectedMethod = "CARD";
        
        cvc.setVisible(true);
        cvcField.setVisible(true);
        
        card.setBackground(Color.GRAY);
        card.setForeground(Color.BLACK);
        
        gcash.setBackground(Color.WHITE);
        gcash.setForeground(Color.GRAY);
        otc.setBackground(Color.WHITE);
        otc.setForeground(Color.GRAY);
        
        
        name.setText("Cardholder Name");
        number.setText("Card Number");
        adress.setText("Expiration");
    }//GEN-LAST:event_cardActionPerformed

    private void otcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otcActionPerformed
        selectedMethod = "OTC";
        
        otc.setBackground(Color.GRAY);
        otc.setForeground(Color.BLACK);
        
        gcash.setBackground(Color.WHITE);
        gcash.setForeground(Color.GRAY);
        card.setBackground(Color.WHITE);
        card.setForeground(Color.GRAY);
        
        name.setText("Name");
        adress.setText("Gmail");
        number.setText("Number");
        
        cvc.setVisible(false);
        cvcField.setVisible(false);
    }//GEN-LAST:event_otcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new paymentOptions().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adress;
    private javax.swing.JTextField adressField;
    private javax.swing.JLabel amount;
    private javax.swing.JButton back;
    private javax.swing.JPanel bottomContainer;
    private javax.swing.JButton card;
    private javax.swing.JButton confirm;
    private javax.swing.JPanel container;
    private javax.swing.JLabel cvc;
    private javax.swing.JTextField cvcField;
    private javax.swing.JButton gcash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel number;
    private javax.swing.JTextField numberField;
    private javax.swing.JButton otc;
    private javax.swing.JPanel topContainer;
    // End of variables declaration//GEN-END:variables
}
