/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lipad_bantay;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.io.*;
/**
 *
 * @author Joshua
 */
public class LB_HomeScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LB_HomeScreen.class.getName());

    /**
     * Creates new form LB_HomeScreen
     */
    public LB_HomeScreen() {
        initComponents();
//        loadTimeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        TopContainer = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SearchContainer = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        SortContainer = new javax.swing.JPanel();
        AirlineSort = new javax.swing.JToggleButton();
        OriginSort = new javax.swing.JToggleButton();
        DestinationSort = new javax.swing.JToggleButton();
        TimeSort = new javax.swing.JToggleButton();
        FrequencySort = new javax.swing.JToggleButton();
        AircraftSort = new javax.swing.JToggleButton();
        BottomContainer = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(255, 255, 255));

        TopContainer.setBackground(new java.awt.Color(51, 153, 255));

        Title.setFont(new java.awt.Font("Santana-Black", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("LIPAD BANTAY");

        SearchContainer.setBackground(new java.awt.Color(255, 255, 255));

        SearchField.setBackground(new java.awt.Color(255, 255, 255));
        SearchField.setText("jTextField1");

        SearchButton.setBackground(new java.awt.Color(0, 102, 255));
        SearchButton.setText("Search");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout SearchContainerLayout = new javax.swing.GroupLayout(SearchContainer);
        SearchContainer.setLayout(SearchContainerLayout);
        SearchContainerLayout.setHorizontalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        SearchContainerLayout.setVerticalGroup(
            SearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SortContainer.setBackground(new java.awt.Color(204, 204, 204));
        SortContainer.setMaximumSize(new java.awt.Dimension(356, 40));
        SortContainer.setMinimumSize(new java.awt.Dimension(356, 40));
        SortContainer.setPreferredSize(new java.awt.Dimension(356, 40));

        AirlineSort.setBackground(new java.awt.Color(0, 153, 255));
        AirlineSort.setText("Ariline Sort");
        AirlineSort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AirlineSort.setMaximumSize(new java.awt.Dimension(120, 35));
        AirlineSort.setMinimumSize(new java.awt.Dimension(120, 35));
        AirlineSort.setPreferredSize(new java.awt.Dimension(120, 35));
        AirlineSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlineSortActionPerformed(evt);
            }
        });

        OriginSort.setBackground(new java.awt.Color(0, 153, 255));
        OriginSort.setText("Origin Sort");
        OriginSort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OriginSort.setPreferredSize(new java.awt.Dimension(120, 35));
        OriginSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriginSortActionPerformed(evt);
            }
        });

        DestinationSort.setBackground(new java.awt.Color(0, 153, 255));
        DestinationSort.setText("Destination Sort");
        DestinationSort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DestinationSort.setPreferredSize(new java.awt.Dimension(120, 35));
        DestinationSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationSortActionPerformed(evt);
            }
        });

        TimeSort.setBackground(new java.awt.Color(0, 153, 255));
        TimeSort.setText("Time Sort");
        TimeSort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TimeSort.setPreferredSize(new java.awt.Dimension(120, 35));
        TimeSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeSortActionPerformed(evt);
            }
        });

        FrequencySort.setBackground(new java.awt.Color(0, 153, 255));
        FrequencySort.setText("Frequency Sort");
        FrequencySort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FrequencySort.setPreferredSize(new java.awt.Dimension(120, 35));
        FrequencySort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrequencySortActionPerformed(evt);
            }
        });

        AircraftSort.setBackground(new java.awt.Color(0, 153, 255));
        AircraftSort.setText("Aircraft Sort");
        AircraftSort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AircraftSort.setMaximumSize(new java.awt.Dimension(120, 35));
        AircraftSort.setMinimumSize(new java.awt.Dimension(120, 35));
        AircraftSort.setPreferredSize(new java.awt.Dimension(120, 35));

        javax.swing.GroupLayout SortContainerLayout = new javax.swing.GroupLayout(SortContainer);
        SortContainer.setLayout(SortContainerLayout);
        SortContainerLayout.setHorizontalGroup(
            SortContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SortContainerLayout.createSequentialGroup()
                .addComponent(AirlineSort, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AircraftSort, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OriginSort, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DestinationSort, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrequencySort, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeSort, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SortContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AircraftSort, AirlineSort, DestinationSort, FrequencySort, OriginSort, TimeSort});

        SortContainerLayout.setVerticalGroup(
            SortContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SortContainerLayout.createSequentialGroup()
                .addGroup(SortContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AirlineSort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AircraftSort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OriginSort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestinationSort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrequencySort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeSort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout TopContainerLayout = new javax.swing.GroupLayout(TopContainer);
        TopContainer.setLayout(TopContainerLayout);
        TopContainerLayout.setHorizontalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(SortContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        TopContainerLayout.setVerticalGroup(
            TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(TopContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(SortContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BottomContainer.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton1.setText("BACK");

        javax.swing.GroupLayout BottomContainerLayout = new javax.swing.GroupLayout(BottomContainer);
        BottomContainer.setLayout(BottomContainerLayout);
        BottomContainerLayout.setHorizontalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BottomContainerLayout.setVerticalGroup(
            BottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomContainerLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        FlightTable.setBackground(new java.awt.Color(255, 255, 255));
        FlightTable.setForeground(new java.awt.Color(0, 0, 0));
        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ariline", "Aircraft", "Origin", "Destination", "Frequency", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(FlightTable);
        if (FlightTable.getColumnModel().getColumnCount() > 0) {
            FlightTable.getColumnModel().getColumn(0).setResizable(false);
            FlightTable.getColumnModel().getColumn(1).setResizable(false);
            FlightTable.getColumnModel().getColumn(2).setResizable(false);
            FlightTable.getColumnModel().getColumn(3).setResizable(false);
            FlightTable.getColumnModel().getColumn(4).setResizable(false);
            FlightTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BottomContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(TopContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
//    public void loadTimeTable(){
//        DefaultTableModel model = (DefaultTableModel) FlightTable.getModel();
//        
//     
//        model.setRowCount(0);
//
//        
//        
//        String path = 
////        File timetableOpen = new File()

        // 4. Loop through and add to table
//        for (String line : rawFlights) {
//            if (!line.trim().isEmpty()) {
//                // Split the string by the dash "-"
//                String[] rowData = line.split("-");
//
//                // Add the row to the table model
//                model.addRow(rowData);
//            }
//        }
    
    
    
    private void jToggleButtonAirlineActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // 1. Create a standard sorter (if you haven't already set one up)
        javax.swing.table.TableRowSorter<javax.swing.table.TableModel> sorter = 
            new javax.swing.table.TableRowSorter<>(FlightTable.getModel());

        // 2. Attach it to the table
        FlightTable.setRowSorter(sorter);

        // 3. The "No List" magic command
        // This sorts Column 0 (Airline) immediately
    sorter.toggleSortOrder(0); 
    }
    
    private void TimeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeSortActionPerformed

    private void OriginSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriginSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OriginSortActionPerformed

    private void DestinationSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinationSortActionPerformed

    private void FrequencySortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrequencySortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrequencySortActionPerformed

    private void AirlineSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlineSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlineSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LB_HomeScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AircraftSort;
    private javax.swing.JToggleButton AirlineSort;
    private javax.swing.JPanel BottomContainer;
    private javax.swing.JPanel Container;
    private javax.swing.JToggleButton DestinationSort;
    private javax.swing.JTable FlightTable;
    private javax.swing.JToggleButton FrequencySort;
    private javax.swing.JToggleButton OriginSort;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchContainer;
    private javax.swing.JTextField SearchField;
    private javax.swing.JPanel SortContainer;
    private javax.swing.JToggleButton TimeSort;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
